### PR TITLE
Crystal: add macOS support

### PR DESCRIPTION
**Pull request by olbat**
Fixes travis-ci/travis-ci#7894

cc @matiasgarciaisaia, @asterite, @jhass, @waj, @will

### CODE REVIEW

**Comment by olbat** [comment]
I have a few question to complete this PR:

1. is there a nightly Crystal build for macOS packages ?
2. is it still necessary to install "shards" by hand
3. should this script be `set -e` ? (if there is there a way to do so)

**Comment by asterite** [comment]
Please don't "at" me, I no longer contribute to Crystal

**Comment by BanzaiMan** [comment]
@asterite Please open a PR to remove your name from the list of maintainers in the build log. Thanks.

**Comment by asterite** [comment]
@BanzaiMan Done! #1118

**Comment by olbat** [comment]
Sorry  asterite, I did not know that ...

Should the `sh.echo 'Crystal for Travis-CI is not officially supported, but is community maintained ... and mention asterite, jhass, waj and will in the issue'` be updated as well ?

**Comment by olbat** [comment]
Sorry asterite, I didn't know that, thank you for the PR :)

**Comment by asterite** [comment]
@olbat No problema 😸

**Comment by BanzaiMan** [comment]
This has been deployed to staging for testing.

**Comment by olbat** [comment]
Nice, what will be the next step(s) ?

**Comment by BanzaiMan** [comment]
Well, no one from the Crystal maintainers group weighed in on the PR, so we'll have to wait for that. (The staging does not have this at the moment.)

**Comment by matiasgarciaisaia** [comment]
Sorry for the delay - this PR looks good to me.

@BanzaiMan I'm new to all this stuff - how does the staging process work? Do you have any link in which to read about that?

Busy days this week, but next one I'll be able to try whatever it's needed for this to be merged 👍

**Comment by olbat** [comment]
Thank you for your answer @matiasgarciaisaia, could you also answer to my [3 questions](https://github.com/travis-ci/travis-build/pull/1117#issuecomment-315732015) so I can eventually improve the PR ?

**Comment by matiasgarciaisaia** [comment]
Hi @olbat!

1. I don't think there's a macOS Crystal nightly build. In fact, I'm not even sure if Linux nightlies are still being built on a nightly basis, but I'll trust you on that.
2. Whenever you `brew install crystal`, you get `shards` too. The same happens if you install on Linux through the official repositories. Once again, no idea about nightlies, but I think it makes sense to build shards from source if you're trying to be on the cutting edge.
3. `set -e` would definitely be nice to have, but I don't think it will be _that_ easy. Maybe there's something on the Travis docs to see how to get it working?

Thanks for your efforts!

**Comment by BanzaiMan** [comment]
@matiasgarciaisaia To test with staging, go to https://staging.travis-ci.org/profile and enable a repo there. (You can enable a repo that's used by production https://travis-ci.org; this will detach the repo from production.) If you don't see the repository you want to use on staging, try resyncing data. The next push to the repository will trigger a build on staging.

**Comment by BanzaiMan** [comment]
The `errexit` option (`set -e`) can have unexpected consequences on the build script. Some commands we end up running anticipate nonzero exit status and deal with the failure. Setting `errexit` could mean that the cleanup is not performed, or the build script dying prematurely.

**Comment by olbat** [comment]
@matiasgarciaisaia Thanks for the answers !
I just need a last precision about my 2nd question: since `shards` is now installed via the crystal deb package, should I remove [the manual install part](https://github.com/olbat/travis-build/blob/7dfde535a6e9ea2598e383cc4896c3d462b32893/lib/travis/build/script/crystal.rb#L27-L33) ?

@BanzaiMan Thank you for your explanations, I understand the issue here ...

**Comment by olbat** [comment]
Erm, I tried to run a build on staging but I still get [the same error](https://staging.travis-ci.org/olbat/libgen/jobs/607495) as before, did I do something wrong ?

**Comment by matiasgarciaisaia** [comment]
@olbat I think [the job](https://staging.travis-ci.org/olbat/libgen/jobs/607495) says it's using [`travis-build` version 72fc95a92](https://staging.travis-ci.org/olbat/libgen/jobs/607495#L10), which [doesn't contain your commit](https://github.com/travis-ci/travis-build/commits/72fc95a921a4df858847817dba82a31fa789948e).

I think that's because the [PR's check failed](https://travis-ci.org/travis-ci/travis-build/builds/255716558). I don't actually get what [the error is about](https://travis-ci.org/travis-ci/travis-build/jobs/255716563#L539-L553) - it seems to be some permissions error while trying to download some dependency, so maybe it's just about re-building the job. Maybe @BanzaiMan can help a little bit with that?

**Comment by olbat** [comment]
@matiasgarciaisaia I've seen this error in other builds from this repository, I think it does not depends on what is tested in this PR ... (another fix / a "Restart job" may be needed)

**Comment by BanzaiMan** [comment]
Could you rebase this PR? There was a problem with external PRs failing due to GitHub API rate limiting.

**Comment by olbat** [comment]
@BanzaiMan done !

**Comment by BanzaiMan** [comment]
This has been deployed to staging.

**Comment by olbat** [comment]
Nice ! It [seems](https://staging.travis-ci.org/olbat/crystal_lib) to be OK :thumbsup:

**Comment by matiasgarciaisaia** [comment]
@olbat I've just checked, and `shards` is effectively installed by just installing the `crystal` package - so you can drop it from the script. For nightly, as I've said, it may make sense to build from `master` - I'm OK with both alternatives.

Other than that, the PR seems 👌

Thank you!

**Comment by olbat** [comment]
@matiasgarciaisaia I removed the shards install from the linux image, I'll not have the time to add builds from master (on macOS ?) before the end of next week ... (holidays, holidays)

If you're OK with that, I'll probably make another PR for this improvement so you can merge this one.

**Comment by matiasgarciaisaia** [comment]
@BanzaiMan this is ready to be merged. After that, I'll add myself as one of the Crystal maintainers 👍

**Comment by olbat** [comment]
Nice ! 🎉

**Pull request merged**
