### PR TITLE
Export CC_FOR_BUILD additionally to CC in C builds

### PR DESCRIPTION
**Pull request by real-or-random**
CC_FOR_BUILD is a common build variable to specify a "build compiler",
i.e., a compiler that creates binaries that run on the compiling host
(instead of the  target system when cross-compiling). This commit ensures
that clang as a build compiler when `compiler: clang` is set.

[0] https://www.gnu.org/software/autoconf-archive/ax_prog_cc_for_build.html

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hello. Please open a corresponding documentation PR. Thank you for your contribution!

**Comment by real-or-random** [comment]
Done

**Comment by BanzaiMan** [comment]
Will deploy Tuesday.

**Comment by real-or-random** [comment]
Sorry, I pressed "Update branch" here but not sure if it was a good idea. Feel free to ignore the merge commit of course.

**Comment by real-or-random** [comment]
Everything alright with this? The corresponding documentation PR was merged but this one wasn't. 
I can force-push here to make that unnecessary merge commit disappear if you would like.

**Comment by meatballhat** [comment]
@real-or-random no worries about the merge commit :+1: I'll merge this shortly.

**Pull request merged**
