### PR TITLE
Update Sauce Connect to 4.3.6

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by joshk** [comment]
DAMN! AWESOME WORK!

**Comment by BanzaiMan** [comment]
Let's test this on staging!

**Comment by r0man** [comment]
Hello,

I noticed that the Sauce Connect tunnels don't get shut down properly since yesterday.
Not sure if this is related to this commit, or the new version of Sauce Connect.
For the moment this seems to help:
```
after_script:
  - killall sc
  - sleep 2
  - killall -9 sc
```

Roman

**Comment by meatballhat** [comment]
@r0man thank you!

**Comment by joshk** [comment]
@meatballhat how should we best deal with this?

**Comment by meatballhat** [comment]
I've got a patch in the works; planning to test in staging and hopefully deploy today

**Pull request merged**
