### PR TITLE
haxe: install by linking into /usr/local

### PR DESCRIPTION
**Pull request by andyli**
Avoid modifying PATH, LD_LIBRARY_PATH, and DYLD_FALLBACK_LIBRARY_PATH.
Fix https://github.com/travis-ci/travis-ci/issues/6748.

### CODE REVIEW

**Comment by andyli** [comment]
It would be great if this can be merged soonish because the current osx_image is using 10.11, which `language: haxe` will fail due to the mentioned issue.

**Comment by andyli** [comment]
@BanzaiMan Would you review this?

**Comment by BanzaiMan** [comment]
Sorry about the delay. I'll deploy this to staging in a bit.

**Comment by BanzaiMan** [comment]
Deployed to staging.

**Comment by andyli** [comment]
Thanks!

There was a mistake, and I've just pushed a fix. Would you deploy to staging again?

**Comment by BanzaiMan** [comment]
@andyli Deployed to staging.

**Comment by andyli** [comment]
It seems to work now! However, the Mac builds never start on staging (is that normal?), so I cannot test the Mac builds. There is nothing Mac-specific, so it should be fine.
Also, the `apt:` addon doesn't seem to work on staging that it said `Disallowing packages: gcc-multilib, ...` for all the packages. I guess that's also a limitation of staging?

**Comment by BanzaiMan** [comment]
@andyli Sorry for the delay in responding. Mac builds may be unstable from time to time on staging. :-(

If it's OK with you, I'd like to merge this and deploy to production so that we can test it.

**Comment by andyli** [comment]
Alright!
Yes, please merge. I will test as soon as possible and will let you know if there is any issue.

**Comment by BanzaiMan** [comment]
@andyli This has been deployed to production.

**Comment by andyli** [comment]
Worked fine with my initial testing! Thanks!

**Pull request merged**
