### PR TITLE
Bump R release to 3.6.1

### PR DESCRIPTION
**Pull request by jeroen**
@jimhester

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hello, there. Specs needs fixing. Instead of matching `3.6.0`, you can be a little more lax in matching version numbers (say, `\d(\.\d)*`).

**Comment by jeroen** [comment]
I don't understand the suggestion. We don't match `3.6.0` anywhere; we just update the alias for `3.6` and `release` to mean `3.6.1`.

**Comment by jimhester** [comment]
The specs do check that the current version matches what we expect it to, so they need to be updated. There is one additional spec you missed, the regex has an escape, so it is easy to miss, here is the diff to fix it. You can run `bundle exec rspec spec/build/script/r_spec.rb` to verify the tests are fixed locally.

```diff
diff --git a/spec/build/script/r_spec.rb b/spec/build/script/r_spec.rb
index f2ee4a23..14566b1d 100644
--- a/spec/build/script/r_spec.rb
+++ b/spec/build/script/r_spec.rb
@@ -54,7 +54,7 @@ describe Travis::Build::Script::R, :sexp do
   end

   it 'downloads and installs latest R' do
-    should include_sexp [:cmd, %r{^curl.*https://travis-ci\.rstudio\.org/R-3\.6\.0-\$\(lsb_release -cs\)\.xz},
+    should include_sexp [:cmd, %r{^curl.*https://travis-ci\.rstudio\.org/R-3\.6\.1-\$\(lsb_release -cs\)\.xz},
                          assert: true, echo: true, retry: true, timing: true]
   end

(END)
```

**Comment by BanzaiMan** [comment]
```
should include_sexp [:cmd, %r{^curl.*https://travis-ci\.rstudio\.org/R-3\.6\.1-\$\(lsb_release -cs\)\.xz},
```
suffers from the same problem; this will break with the next update.

**Comment by jeroen** [comment]
> suffers from the same problem; this will break with the next update.

So do you suggest we match relax the test to match any version? Doesn't that defeat the purpose of that we are trying to test here?

Either way I updated the PR to fix the versions everywhere.

**Comment by jimhester** [comment]
Thanks for updating it, LGTM now.

**Pull request merged**
