### PR TITLE
C#: only add the wheezy-libtiff-compat apt repository on Ubuntu 12.04

### PR DESCRIPTION
**Pull request by akoeplinger**
This allows the script to work on Ubuntu 14.04.

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
It might be cleaner to check if `config['dist'] != 'trusty'` than running a check in the script itself.

**Comment by akoeplinger** [comment]
That won't work with the docker service, see the conversation on Slack. This doesn't fully work yet, I forgot to mark as WIP :)

**Comment by Joshua-Anderson** [comment]
Docker builds also run on trusty, so I believe dist should be set to  trusty when the job is processed.

**Comment by akoeplinger** [comment]
It isn't, that's the problem.

**Comment by Joshua-Anderson** [comment]
Just read slack, code LGTM! Sorry about that.

**Pull request merged**
