### PR TITLE
baseline key for smalltalk

### PR DESCRIPTION
**Pull request by jchromik**
We just added the baseline key support in smalltalk.rb as requested in pull request [#419](https://github.com/travis-ci/docs-travis-ci-com/pull/419) of [travis-ci/docs-travis-ci-com](https://github.com/travis-ci/docs-travis-ci-com/).

### CODE REVIEW

**Comment by fniephaus** [comment]
It'd be great to get this in soon, since it contains an important SSL fix.

**Comment by fniephaus** [comment]
Wow, that was quick. Thanks @BanzaiMan!

**Comment by BanzaiMan** [comment]
Sorry for the delay. This has been deployed to staging. Please test it.

**Comment by fniephaus** [comment]
Mhh, any idea why `SMALLTALK` is expanding as intended, but `BASELINE` isn't?

```ruby
sh.export 'SMALLTALK', config[:smalltalk], echo: false
sh.export 'BASELINE', config[:baseline], echo: false
```

See e.g.:
https://staging.travis-ci.org/fniephaus/SWT-Demo/builds/465759#L242

**Comment by BanzaiMan** [comment]
Matrix expansion requires changes in `travis-core`.

**Comment by Nef10** [comment]
see: https://github.com/HPI-BP2015H/travis-core/blob/cf7c5656d02e8bebcd046dc0fc1a7af250e987cf/lib/travis/model/build/config.rb

**Comment by BanzaiMan** [comment]
I'm afraid we are not going to deploy that change to production before the holidays.

Specifying `baseline` with a scalar value should work, though.

**Comment by fniephaus** [comment]
That'd totally be fine for now. And I can confirm it works fine:
https://staging.travis-ci.org/fniephaus/SWT-Demo/builds/465761

@Nef10: can you update the correspondig docs pull request and remove multiple baselines? Just do:
```
baseline: MyProjectBaseline
```
We can add support for multiple baselines as soon as someone actually needs it (haven't seen a project with multiple baselines yet).

@BanzaiMan can this still be deployed then before the holidays? The SSL fix is quite important.

**Comment by Nef10** [comment]
Done: https://github.com/HPI-BP2015H/docs-travis-ci-com/commit/8f15caafcc42f5c2aae749a61d8f821ba3b3e5a9

**Comment by BanzaiMan** [comment]
This has been deployed to production.

**Comment by fniephaus** [comment]
Thanks!

**Pull request merged**
