### PR TITLE
[community:r] Support BiocManager for next release of Bioconductor

### PR DESCRIPTION
**Pull request by LiNk-NY**
* Updated the tests to reflect the use of BiocManager
* `bioc_install_script` and `bioc_install_bioccheck` are conditional on the R version (>= or < `3.5.0`)
* separated tests to run against `bioc-release` and `bioc-devel` options

cc: @jimhester

### CODE REVIEW

**Comment by jimhester** [comment]
I would really prefer not to need to maintain multiple code paths for this, is there really no way BiocManager could not handle backwards compatibility for previous R versions?

**Comment by LiNk-NY** [comment]
I've talked to Martin about this @mtmorgan and there doesn't seem to be a viable solution to 
supporting older versions of R from `BiocManager`. 
Could you provide some insight Martin? Thanks.

**Comment by jimhester** [comment]
Well travis supports R versions back to 3.1, so ideally back that far at least.

**Comment by LiNk-NY** [comment]
Hi Jim, @jimhester 
Any updates on this? 
Currently, Bioconductor packages cannot be tested with Travis...

Best regards,
Marcel

**Comment by jimhester** [comment]
It looks fine to me, however someone from travis will have to review, merge and deploy it.

**Comment by csoneson** [comment]
Thanks Marcel @LiNk-NY, this is great. I don't know if I'm missing something, but after this PR was merged, I am running into problems with my travis build (build report is here: https://travis-ci.com/csoneson/Rhisat2, travis config file here: https://github.com/fmicompbio/Rhisat2/blob/master/.travis.yml). (It has built well previously). It seems that travis is complaining about syntax errors in one of the lines introduced in this PR (when checking for BiocManager). The same problem can be seen also in other Bioconductor packages with recent build attempts (e.g. https://travis-ci.org/federicomarini/pcaExplorer). If you have any insights, that would be very helpful. Thanks!

**Comment by LiNk-NY** [comment]
Hi Charlotte, @csoneson 
This has been fixed in the most recent PR. It might take some time to reflect in the builds.
Apologies for the inconvenience. 
-Marcel

**Comment by csoneson** [comment]
Oh great, thanks! No worries, thanks for doing this!

**Comment by LiNk-NY** [comment]
Hi Heather, @hturner 
This is a known issue and Jim Hester has been working on it.
Thanks for reporting! 
See https://github.com/travis-ci/travis-build/pull/1580 for more info.

**Comment by hturner** [comment]
Ah that's great, thanks for letting me know!

**Pull request merged**
