### PR TITLE
Update gimme to support `.x` Go versions

### PR DESCRIPTION
**Pull request by cotsog**

### CODE REVIEW

**Comment by cotsog** [comment]
Release notes: https://github.com/travis-ci/gimme/releases/tag/v1.5.0

**Comment by dmitshur** [comment]
This is strange, but I’ve seen gimme v1.5.0 already used in my previous builds.

Additionally, the recent fix (
https://github.com/travis-ci/gimme/pull/153) is not included in gimme v1.5.0, a newer release will need to be created. See the first paragraph of 
https://github.com/travis-ci/travis-ci/issues/9652#issuecomment-409789014.

**Comment by cotsog** [comment]
@dmitshur you are right, it seems that gimme updates itself in the build so we already are using 1.5.0.

We'll try to get [a gimme v1.5.1 release](https://github.com/travis-ci/gimme/pull/156) and it should be incorporated in a build automatically.

Thank you for your patience and I'm closing this one in the meantime.

**Comment by dmitshur** [comment]
> We'll try to get [a gimme v1.5.1 release](https://github.com/travis-ci/gimme/pull/156) and it should be incorporated in a build automatically.

Following up on this. The gimme [v1.5.1 release](https://github.com/travis-ci/gimme/releases/tag/v1.5.1) has been created 6 days ago, but a [very recent Travis build](https://travis-ci.org/shurcooL/home/jobs/415246927) is still picking up gimme v1.5.0. Do you know what else needs to be done for Travis CI to start using the latest gimme v1.5.1? Thank you!

**Comment by dmitshur** [comment]
@cotsog Thanks for following up.

I created a new branch in one of my repos, which triggered a new build. Its output is here:

https://travis-ci.org/shurcooL/home/jobs/416164962

You can see there that `gimme version` still prints `v1.5.0`, and the Go version selected is `go1.11rc1` rather than `go1.10.3`. So it doesn't seem be to working yet.

**Comment by joepvd** [comment]
Hi @dmitshur. I think it looks better now. Apologies for the back-and-forth.

**Comment by dmitshur** [comment]
Confirmed! I’ve restarted [the same build](https://travis-ci.org/shurcooL/home/jobs/416164962) again, and this time I see:

```
Updating gimme
…
$ gimme version
v1.5.1
$ go version
go version go1.10.3 linux/amd64
```

I’m very happy to confirm this issue is now resolved. Thank you very much!

**Pull request closed without merging**
