### PR TITLE
Double-quote variable values for `set` and `export` commands

### PR DESCRIPTION
**Pull request by native-api**
https://travis-ci.community/t/sonarqube-plugin-failing-due-to-failed-export/7429

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Planning to merge and deploy on Monday.

**Comment by daviddavis** [comment]
I think one of these changes might have broken Travis variables: https://travis-ci.community/t/travis-incorrectly-double-quotes-environment-variables/7496

**Comment by BanzaiMan** [comment]
Sorry about that. We've reverted this and deployed the revert. Please restart the affected build(s). We'll look at the issue that this PR aimed to address at a later time.

**Comment by native-api** [comment]
As per https://travis-ci.community/t/travis-incorrectly-double-quotes-environment-variables/7496/9, this turns out to be an undocumented grey area thus the behavior change wasn't caught by tests.

We should decide what the expected behavior would be before trying this again.

Why [unquoting doesn't restore the old behavior](https://travis-ci.community/t/travis-incorrectly-double-quotes-environment-variables/7496/8?u=native-api) is a mystery to me for now.

**Comment by native-api** [comment]
> Why [unquoting doesn't restore the old behavior](https://travis-ci.community/t/travis-incorrectly-double-quotes-environment-variables/7496/8?u=native-api) is a mystery to me for now.

For the record, found it. https://github.com/travis-ci/travis-build/blob/872488641f195b168f22c67bc0aff1062e63a4c6/lib/travis/build/env/var.rb#L13 splits at whitespace if there are no quotes -- to allow multiple `var=value` pairs per entry.

**Pull request merged**
