### PR TITLE
update version 1 to point to Julia 1.2

### PR DESCRIPTION
**Pull request by PhilipVinc**
Current stable version is 1.2

cc
@ararslan
@staticfloat
@StefanKarpinski

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Bump?

**Comment by StefanKarpinski** [comment]
Has two approvals, seems good to go.

**Comment by BanzaiMan** [comment]
Coincidentally… is there a way to discover what `1` should mean?

**Comment by StefanKarpinski** [comment]
You mean programmatically or as a human? It's the latest 1.x release, currently 1.2, soon 1.3.

**Comment by BanzaiMan** [comment]
@StefanKarpinski Programmatically. Rather than relying on humans to send PRs when a new relevant release comes, it would be great if `1` could mean "latest stable 1.x.y release" instead. I know this is not entirely possible or desirable, but it is worth considering.

**Comment by StefanKarpinski** [comment]
@staticfloat, what do you think? Do we have a programmatic way to get this info?

**Comment by ararslan** [comment]
We do not currently, but it's something we've wanted to set up for a while. It would be as simple as what we do now to get x.y-latest URLs: just make a 1-latest on S3.

**Comment by staticfloat** [comment]
We could also conceivably set up a JSON file that has a bunch of information; things like "here are all the Julia versions ever, here's the latest 1.X.Y, here's the latest 1.X, etc....".  Which would be most useful to you?

**Pull request merged**
