### PR TITLE
Julia: Split out build steps into different sections

### PR DESCRIPTION
**Pull request by simonbyrne**
This should hopefully solve the coverage/assertion issues (#1568 #1450), and make the code much simpler.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Spec's expectation needs fixing.

**Comment by simonbyrne** [comment]
I don't quite understand what the spec does, or why it's failing (there is still a `curl` call there, I just moved it to a different section). Any suggestions?

**Comment by iamed2** [comment]
I think it's seeing
```
[:cmd, "curl -A \"$CURL_USER_AGENT\" -s -L --retry 7 'https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6-latest-linux-x86_64.tar.gz' | tar -C ~/julia -x -z --strip-components=1 -f -"]
```
but it's expecting 
```
[:cmd, "curl -A \"$CURL_USER_AGENT\" -s -L --retry 7 'https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6-latest-linux-x86_64.tar.gz' | tar -C ~/julia -x -z --strip-components=1 -f -", {:assert=>true, :echo=>true, :retry=>true, :timing=>true}]
```

**Comment by ararslan** [comment]
Looks like the branch needs to be rebased, but CI is green :tada:

**Comment by simonbyrne** [comment]
Thanks @iamed2 !

**Comment by simonbyrne** [comment]
@BanzaiMan Could we try this out on staging please?

**Comment by BanzaiMan** [comment]
@simonbyrne This has been deployed to https://staging.travis-ci.org.

**Comment by simonbyrne** [comment]
Okay, so this works pretty well, and gives the correct errors. The main downside is that if users are already defining these steps in their own files then the job will fail. 

The most likely problem will probably be the `install` step, however both PyCall and RCall use `before_install`, so they won't have that problem. I'm not sure if there are others.

I might move the coverage upload to `after_after_success`, since that is less likely to be overwritten than `after_success`.

**Comment by simonbyrne** [comment]
Even at the risk of breakage, I think this is a worthwhile change, since it (a) does make it consistent with other languages, and (b) makes it easier to users to overwrite specific parts of the code, e.g. if they need to inject something between the `install` step (`Pkg.build`) and the `script` step (`Pkg.test`).

**Comment by simonbyrne** [comment]
@BanzaiMan can you deploy this to staging again so I can try out the coverage with it in `after_after_success`?

**Comment by BanzaiMan** [comment]
Deployed to org staging now.

**Comment by simonbyrne** [comment]
I guess I can just move it to `after_success` for now, since this won't break existing functionality, and Julia doc builds are moving to their own separate stage.

**Comment by simonbyrne** [comment]
@BanzaiMan Can you deploy to staging once more?

**Comment by BanzaiMan** [comment]
Deployed again.

**Comment by simonbyrne** [comment]
Hmm, that still doesn't work: https://staging.travis-ci.org/JuliaCI/TravisTest.jl/jobs/728725

Any ideas?

**Comment by BanzaiMan** [comment]
I _think_ those require additional care to trigger. The details are escaping me at the moment. I'll take a look again soon.

**Comment by omus** [comment]
Bump

**Comment by jayvdb** [comment]
Needs a rebase.

**Comment by jayvdb** [comment]
ping @simonbyrne

**Comment by simonbyrne** [comment]
@jayvdb done.

**Comment by ararslan** [comment]
I've done another rebase, as there were merge conflicts.

**Comment by christopher-dG** [comment]
bump, could someone rebase this?

**Comment by ararslan** [comment]
Bump. The PR is rather stale, could do with another rebase if you get the time, @simonbyrne.

**Comment by simonbyrne** [comment]
Done. Unfortunately I don't remember how this works so 🤷‍♂️

**Comment by ararslan** [comment]
Actually, it looks like this PR is so old that the rebase removed a lot of the functionality that's since been added (e.g. multi-arch, Windows, and FreeBSD).

**Comment by ararslan** [comment]
If you'd like, we can close this and I can try to re-apply this refactoring overtop of the most recent work.

**Comment by simonbyrne** [comment]
I don't really have time to spend on this, so if someone wants to fork it and try again, feel free.

**Comment by ararslan** [comment]
I'll give that a go (though anyone else should also feel free to try). Thanks so much for your efforts here, Simon; you've laid a good groundwork. :)

**Pull request closed without merging**
