### PR TITLE
Add `brew` addon

### PR DESCRIPTION
**Pull request by BanzaiMan**
For more declarative Homebrew package installation

### CODE REVIEW

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/5377.

**Comment by BanzaiMan** [comment]
Test: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/538832

**Comment by AraHaan** [comment]
Does this brew imply linux brew on linux so that way people needing to use that to install the latest C/C++ compilers while apt-get fails to work for them to not have to manually install it. Otherwise I approve the changes.

**Comment by BanzaiMan** [comment]
@AraHaan No. This is for Homebrew.

**Comment by AraHaan** [comment]
ok then.

**Comment by AraHaan** [comment]
well it looks like the approval did nothing to the mergeability of this PR.

**Comment by xoviat** [comment]
@BanzaiMan is there any update on this? It seems like a simple but useful change.

**Comment by BanzaiMan** [comment]
Closing this in favor of #1467.

**Comment by kbrock** [comment]
thanks @BanzaiMan

**Pull request closed without merging**
