### PR TITLE
Nix: fix macOS install by using 'yes'

### PR DESCRIPTION
**Pull request by domenkozar**
Nix 1.11.12 was released that uses interactive mode for macOS, so this commit fixes that.

I haven't tested this change, so if @BanzaiMan can deploy it to staging I'm happy to give it a spin.

cc @garbas @matthewbauer

### CODE REVIEW

**Comment by BanzaiMan** [comment]
This has been deployed to staging.

**Comment by domenkozar** [comment]
Waiting on https://staging.travis-ci.org/hercules-ci/hercules/jobs/602517

**Comment by domenkozar** [comment]
@BanzaiMan ready for another try.

**Comment by BanzaiMan** [comment]
e187000 has been deployed to staging.

**Comment by domenkozar** [comment]
@BanzaiMan sorry, another fix :)

**Comment by BanzaiMan** [comment]
0267c32 has been deployed to staging.

**Comment by matthewbauer** [comment]
Looks good as a short term fix.

Long term, though, can we maybe get some args for the install script like "--noninteractive" and "--quiet"? That's a lot of extra data for the log that is pretty much unneeded.

https://github.com/NixOS/nix/pull/1453#issuecomment-315225451

**Comment by domenkozar** [comment]
@BanzaiMan I pushed another fix, can you redeploy? Thanks!

**Comment by BanzaiMan** [comment]
@domenkozar 9ba6ea5 has been deployed to staging.

**Comment by domenkozar** [comment]
@BanzaiMan thanks, that caught another problem with `sed` on macOS. Hopefully last time now.

**Comment by BanzaiMan** [comment]
cb87a62 has been deployed to staging.

**Comment by domenkozar** [comment]
@BanzaiMan new round of fixes were needed.

**Comment by BanzaiMan** [comment]
879f5aa has been deployed to staging.

**Comment by domenkozar** [comment]
@BanzaiMan are you sure it is? https://staging.travis-ci.org/hercules-ci/hercules/jobs/602970#L513 doesn't show the `sudo` call I've added

**Comment by BanzaiMan** [comment]
Oops! Sorry. I did so now.

**Comment by domenkozar** [comment]
@BanzaiMan I hope you don't hate me already, pushed another typo fix.

**Comment by BanzaiMan** [comment]
Ha ha ha. No worries. f4505fb has been deployed to staging.

**Comment by BanzaiMan** [comment]
Please fix the specs, though. :-)

**Comment by domenkozar** [comment]
@BanzaiMan what do you mean by specs? :) I pushed another fix :)

**Comment by BanzaiMan** [comment]
Ah. The build failure was spurious. I pushed 3eeedde to staging.

**Comment by domenkozar** [comment]
@BanzaiMan it works! :) https://staging.travis-ci.org/hercules-ci/hercules/builds/602969

Can you deploy this to prod?

**Pull request merged**
