### PR TITLE
announce version with addon: mariadb

### PR DESCRIPTION
**Pull request by grooverdan**

### CODE REVIEW

**Comment by grooverdan** [comment]
sorry, i'm a bit lost of writing ruby test cases.

**Comment by BanzaiMan** [comment]
No worries. Addons don't get their `#announce` invoked, so we'll have to figure something out if we are to do something about it. It's getting late here now, but I'll take a look at this some time next week.

**Comment by joshk** [comment]
Can we just announce the version installed when we install it?

**Comment by BanzaiMan** [comment]
I added a command to announce this at the end of the addon invocation. See @940fd45.

**Comment by grooverdan** [comment]
@940fd45 is incorrect as it announces the mysql client version not the server version.

**Pull request closed without merging**
