### PR TITLE
Enable code coverage data and colored output for Julia testing

### PR DESCRIPTION
**Pull request by tkelman**
Running a Julia package's tests with `coverage=true` generates a set of `.jl.cov` files, which can be uploaded to a service like Coveralls using a separate `after_success` snippet. This is being done pretty commonly across Julia packages, and forcing them all to manually re-create the default test script contents plus this small change.

Additionally, colored output has been requested here https://github.com/JuliaCI/TravisTest.jl/issues/1

### CODE REVIEW

**Comment by tkelman** [comment]
Bump. Any feedback?

**Comment by BanzaiMan** [comment]
Sorry, I missed this. Is there any objections for merging? @tkelman @ninjin @staticfloat

**Comment by staticfloat** [comment]
This looks good to me.  @BanzaiMan I like how you tagged @tkelman, even though he's the one who opened this PR.  ;)

**Comment by ninjin** [comment]
@BanzaiMan: Looks good to me.

**Comment by tkelman** [comment]
> @BanzaiMan I like how you tagged @tkelman, even though he's the one who opened this PR. ;)

I have been known to change my mind before! Thanks for taking a look.

I did ask @jakebolewski to open an issue on travis-ci/travis-ci if he gets impatient since presumably that would make it easier for Travis folks to track this, but I guess he didn't get impatient enough.

**Comment by tkelman** [comment]
Thanks @BanzaiMan!

**Comment by tkelman** [comment]
D'oh, this apparently broke things on release Julia because of a bug with command line arguments being stupidly picky that we've fixed on master but not backported. Fix incoming.

**Pull request merged**
