### PR TITLE
Upgrade default Python from 3.6 on Trusty to 3.8 on Xenial

### PR DESCRIPTION
**Pull request by cclauss**
A continuation of #1678 now that [__dist: xenial is the Travis CI default__](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment) we can upgrade from Python 3.6 to 3.7 as the default Python on Travis CI Linux jobs.

Python 3.7 has a slightly stricter syntax than 3.6 because __async__ and __await__ are keywords in Python >= 3.7.  For projects that use Travis CI with the default Python, this pull request will allow them to find these issues before their users do. 

__NOTE:__ This pull request currently ___comments out one test___ which is run on the Trusty-based `travisci/ci-garnet`container because Python 3.7 does not run on Trusty.  Please let me know if this is acceptable or provide guidance on how to run that test on Xenial or later.

### CODE REVIEW

**Comment by cclauss** [comment]
@BanzaiMan @MariadeAnton Can anyone please help me to understand the failure message?
https://travis-ci.org/travis-ci/travis-build/jobs/558975609#L746

**Comment by native-api** [comment]
I believe `docker` is preinstalled, no need to install anything.
https://docs.travis-ci.com/user/docker/
https://travis-ci.org/native-api/test_travis/builds/565893910

And I really don't see why this PR attempts to add it.

**Comment by cclauss** [comment]
https://docs.travis-ci.com/user/reference/xenial/#third-party-apt-repositories-removed

**Comment by native-api** [comment]
By "I don't see why", I meant because Docker is completely irrelevant to Python's default version thus to this PR's topic.

**Comment by cclauss** [comment]
Our only failing test is [__Travis::Build::Script::Python behaves like a bash script full docker container execution runs and passes__](https://travis-ci.com/travis-ci/travis-build/jobs/221164964#L726).  Do you believe this is not a useful test?

**Comment by native-api** [comment]
Docker tests [are run in `travisci-ci-garnet` container](https://travis-ci.com/travis-ci/travis-build/jobs/221197364#L517) which is Trusty-based. And [3.7 is not available for Trusty](https://github.com/travis-ci/docs-travis-ci-com/pull/2413/files#diff-59341367ad69f7bd58902df32ee48600R129-R135).

**Comment by cclauss** [comment]
> Docker tests are run in travisci/ci-garnet container which is Trusty-based. And 3.7 is not available for Trusty.

Thanks @native-api  Where would I fix that test given that Trusty is EOL?

**Pull request closed without merging**
