### PR TITLE
Add APT proxy when available and healthy

### PR DESCRIPTION
**Pull request by meatballhat**
and remove some log noise and superfluous OS checks, too.

### CODE REVIEW

**Comment by meatballhat** [comment]
Related to https://github.com/travis-ci/travis-ci/issues/9112

**Comment by BanzaiMan** [comment]
Let's test it! 🚀

**Comment by meatballhat** [comment]
Example job where the APT mirror is installed: https://staging.travis-ci.org/meatballhat/yolo-octo-adventure/builds/736277

and some of the correlating log lines from squignix:

```
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 302 GET "http://toolbelt.heroku.com:80/ubuntu/./InRelease" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://dl.hhvm.com:80/ubuntu/dists/trusty/InRelease" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://ppa.launchpad.net:80/git-core/ppa/ubuntu/dists/trusty/InRelease" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://apt.postgresql.org:80/pub/repos/apt/dists/trusty-pgdg/InRelease" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://security.ubuntu.com:80/ubuntu/dists/trusty-security/InRelease" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: MISS 404 GET "http://heroku-toolbelt.s3.amazonaws.com:80/apt/InRelease" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 302 GET "http://toolbelt.heroku.com:80/ubuntu/./Release" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://heroku-toolbelt.s3.amazonaws.com:80/apt/Release" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://ppa.launchpad.net:80/pollinate/ppa/ubuntu/dists/trusty/InRelease" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: MISS 404 GET "http://archive.ubuntu.com:80/ubuntu/dists/trusty/InRelease" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://archive.ubuntu.com:80/ubuntu/dists/trusty-updates/InRelease" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 302 GET "http://toolbelt.heroku.com:80/ubuntu/./Release.gpg" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://heroku-toolbelt.s3.amazonaws.com:80/apt/Release.gpg" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://dl.hhvm.com:80/ubuntu/dists/trusty/main/binary-amd64/Packages.gz" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://apt.postgresql.org:80/pub/repos/apt/dists/trusty-pgdg/main/binary-amd64/Packages.gz" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://archive.ubuntu.com:80/ubuntu/dists/trusty-backports/InRelease" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://archive.ubuntu.com:80/ubuntu/dists/trusty/Release" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://archive.ubuntu.com:80/ubuntu/dists/trusty/Release.gpg" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://ppa.launchpad.net:80/git-core/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages.gz" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)"
Nov 27 22:41:26 staging-1-build-cache-l63c squignix: HIT 200 GET "http://apt.postgresql.org:80/pub/repos/apt/dists/trusty-pgdg/main/binary-i386/Packages.gz" HTTP/1.1 [27/Nov/2018:22:41:26 +0000] 10.20.0.2 "Debian APT-HTTP/1.3 (1.2.10)" 
```

**Comment by pevik** [comment]
@meatballhat I didn't get how to use it to fix travis-ci/travis-ci#9112 issue. Any hint?

**Pull request merged**
