### PR TITLE
Default Elixir builds to Elixir 1.0.4 and OTP 17.5.

### PR DESCRIPTION
**Pull request by DevL**
[Elixir 1.0.4](https://github.com/elixir-lang/elixir/releases/tag/v1.0.4) now supports OTP 17.5.

### CODE REVIEW

**Comment by DevL** [comment]
I take it that you also need to install the binaries for OTP 17.5 and Elixir 1.0.4 on the Travis build servers.

**Comment by BanzaiMan** [comment]
This will have to wait until the image with OTP Release 17.5 is released. (Some time tomorrow.)

**Comment by DevL** [comment]
Cool, thanks for the heads up regarding the timeline!

**Comment by BanzaiMan** [comment]
Thanks for alerting to Elixir 1.0.4, by the way. The build environment update would have missed it.

**Comment by DevL** [comment]
No problem. Anything we can do to automate the inclusion of the latest Elixir version in build updates?

**Comment by BanzaiMan** [comment]
That's an interesting idea. It is certainly possible, but I am not sure if it works as expected. It will still depend on what time the image was created.

I think manually specifying them is OK for now.

**Comment by DevL** [comment]
Ok, so making it part of a checklist of some sort if it's not already.

**Pull request closed without merging**
