### PR TITLE
Update 1 to point to 1.4

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by ararslan** [comment]
I think the CI will be fixed by https://github.com/travis-ci/travis-build/pull/1881.

**Comment by abelsiqueira** [comment]
Thanks

**Comment by kimikage** [comment]
Thank you for supporting v1.4.:+1: However, it causes a problem on windows.
https://travis-ci.community/t/support-for-julia-1-4-0-windows-installer-inno-setup/7931

cc: @ararslan

**Comment by ararslan** [comment]
@musm ^

**Comment by kimikage** [comment]
Well, the problem is not with the installer itself, but simply with the branch condition. The "1" means "1.4" *now*.
https://github.com/travis-ci/travis-build/blob/ab196aed5b227288a2f4dcb5c7822868b430b110/lib/travis/build/script/julia.rb#L70-L74

an ad-hoc measure:
```diff
-if config[:julia] == 'nightly' || Gem::Version.new(config[:julia]) >= Gem::Version.new('1.4') 
+if config[:julia] =~ /^(?:nightly|1)$/ || Gem::Version.new(config[:julia]) >= Gem::Version.new('1.4') 
```

**Pull request merged**
