### PR TITLE
BrowserStack App Automate Support

### PR DESCRIPTION
**Pull request by ray-pankaj**
This will allow users to use [BrowserStack app-automate](https://app-automate.browserstack.com/) in their travis-ci builds.
[Documentation](https://www.browserstack.com/docs?product=app-automate) for app-automate tests on BrowserStack.
Is it possible to test this on a staging environment before merging?

### CODE REVIEW

**Comment by BanzaiMan** [comment]
This has been deployed to https://staging.travis-ci.org for testing.

**Comment by iriberri** [comment]
Hi @BanzaiMan (also @joepvd) - according to @ray-pankaj this seems to be working as expected in staging. What would be the next steps?

Thanks!

**Comment by BanzaiMan** [comment]
@ray-pankaj Sorry for the delay. I think we'll need a documentation update to https://docs.travis-ci.com/user/browserstack/.

I'll go ahead and merge this while we wait for the docs PR.

Thanks.

**Comment by ray-pankaj** [comment]
> @ray-pankaj Sorry for the delay. I think we'll need a documentation update to https://docs.travis-ci.com/user/browserstack/.
> 
> I'll go ahead and merge this while we wait for the docs PR.
> 
> Thanks.

@BanzaiMan Thanks. I will be updating the docs soon.

**Pull request merged**
