### PR TITLE
TRAVIS-14 Replace sonarqube.com by sonarcloud.io

### PR DESCRIPTION
**Pull request by dbmeneses**
SonarQube.com has been renamed to SonarCloud.io and we need to update the addon accordingly.
I left the sonarqube addon (with a warning) for compatibility with yml files that are currently using it. We can remove it in a couple of months.
More information here: https://jira.sonarsource.com/browse/MMF-921

### CODE REVIEW

**Comment by bellingard** [comment]
To be perfectly precise, "SonarQube.com" has been rebranded to "SonarCloud" - not "SonarCloud.io".
(cc @dbmeneses :-) )

**Comment by BanzaiMan** [comment]
Hello. This has been deployed to https://staging.travis-ci.org. Let us know how it goes.

**Comment by bellingard** [comment]
I've validated this on [staging](https://staging.travis-ci.org/FabOrga/multi-language-multi-module-project).

So all good on my side @BanzaiMan !

@dbmeneses: I think you can submit the P/R for the documentation too. Thanks!

**Comment by dbmeneses** [comment]
@BanzaiMan I created a P/R for the doc: https://github.com/travis-ci/docs-travis-ci-com/pull/1262. From our side we're ready to go to prod.

**Pull request merged**
