### PR TITLE
Update HHVM on Precise

### PR DESCRIPTION
**Pull request by BanzaiMan**
Since our support on Precise is ending, we do not have a chance to update HHVM to anything newer than 3.5 that we currently have.

HHVM has terminated [Precise support at 3.6.x](https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Ubuntu-12.04), so we handle this special case.

On future releases and OS X, we do not update HHVM, as we assume that it is reasonably up-to-date.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Tested here: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/439173#L95-L96

**Comment by meatballhat** [comment]
@BanzaiMan Does this also mean we (meaning myself and @solarce) can remove HHVM from the next precise image update?

**Comment by BanzaiMan** [comment]
@meatballhat Is there a Precise update scheduled?

**Comment by BanzaiMan** [comment]
@meatballhat Let's leave it there for now. If the update includes the latest 3.6.x HHVM, then this update step would be a no-op (though it adds a few seconds to the build). It is easy enough to revert it.

**Comment by meatballhat** [comment]
@BanzaiMan There is a precise update in the works, so it's scheduled-ish, with a deadline of "before 2016".

**Pull request merged**
