### PR TITLE
Uninstall oclint when running on Mac

### PR DESCRIPTION
**Pull request by BanzaiMan**
This package is interfering with other more important packages such
as gcc. So we remove it on the fly.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Test: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/731393

**Comment by BanzaiMan** [comment]
and https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/731398

**Comment by BanzaiMan** [comment]
Xcode6.4 does not seem to work; I tend to think it is a general problem with that image.

**Comment by mjm** [comment]
Looks like Homebrew is broken, it doesn't seem to update successfully. Homebrew doesn't officially support an OS that old anymore. I'm not sure what we can do there :(

**Comment by BanzaiMan** [comment]
Right. The image doesn't have Ruby 2.3, which is required for the current Homebrew, but installing Ruby 2.3 itself will require dependencies to be installed via—you guessed it—Homebrew. We've announced deprecation of Xcode6.4 for January, 2019, but it might be beyond salvation now.

**Comment by mjm** [comment]
I'm inclined to agree. I think it'll just have to remain in its current state, and anyone who is still able to use it can until January.

**Pull request merged**
