### PR TITLE
[community: r] clean up quotes

### PR DESCRIPTION
**Pull request by LiNk-NY**

### CODE REVIEW

**Comment by jimhester** [comment]
Thanks, looks good to me, the three levels of escaping you have to work through (ruby, bash, R) is always a good time!

**Comment by wlandau** [comment]
Come to think of it, I have had to click "Restart Build" more often these days due to network issues. Could that be related?

**Comment by LiNk-NY** [comment]
The `r.rb` script does not do anything with network modules AFAICT...

**Comment by wlandau** [comment]
Thanks for your work on repairing this. The quoting issue appears fixed, but it appears that Travis is no longer finding a CRAN mirror. For [this build](https://travis-ci.org/ropensci/drake/builds/452470577?utm_source=github_status&utm_medium=notification), I tried to set a mirror in [`.travis.yml`](https://github.com/ropensci/drake/blob/master/.travis.yml#L7), but this appears to have had no effect.

**Comment by jimhester** [comment]
@wlandau I observed this as well, it stems from the order in which the export and configure blocks run. https://github.com/travis-ci/travis-build/pull/1580 should fix it.

**Comment by wlandau** [comment]
Thanks, Jim!

**Pull request merged**
