### PR TITLE
Add support for running browser tests in dart builds.

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by a14n** [comment]
This is a work in progress. I still face an error in some tests I made.

However, I'd like to have a feedback on my current diff. Particularly the differences between `setup` and `configure` stages. I haven't found a doc to explain the differences. Regarding the list in `travis/build/stages.rb` it looks like I can use sudo in `configure` but not in `setup` (because of `disable_sudo` between them). Am I right ?

**Comment by a14n** [comment]
During my tests I face several problems with _test_runner_ .

I have created a branch `content_shell` on my [dart-rational package](https://github.com/a14n/dart-rational) where I have customized the build with a [.travis.yml](https://github.com/a14n/dart-rational/blob/content_shell/.travis.yml) to do the same thing as in this PR.

In the following error logs I always use the same code (by triggering a build with `git commit --amend && git push -f origin content_shell`)

In [build 5](https://travis-ci.org/a14n/dart-rational/builds/49240083):

```
Detailed results of test suite rational_test.dart:
┌─────────────────────────────────────────────────
│ 
│ Cannot create link, path = '/home/travis/build/a14n/dart-rational/packages/unittest' (OS Error: File exists, errno = 17)
└─────────────────────────────────────────────────
Test suite passed: bigint_test.dart
Test suite failed: rational_browser_test.dart
Detailed results of test suite rational_browser_test.dart:
┌─────────────────────────────────────────────────────────
│ The test did not complete in less than 240 seconds. It was aborted.
└─────────────────────────────────────────────────────────
```

In [build 6](https://travis-ci.org/a14n/dart-rational/builds/49285682) :

```
Detailed results of test suite rational_browser_test.dart:
┌─────────────────────────────────────────────────────────
│ The test did not complete in less than 240 seconds. It was aborted.
└─────────────────────────────────────────────────────────
```

In [build 7](https://travis-ci.org/a14n/dart-rational/builds/49287140) :

```
Detailed results of test suite rational_browser_test.dart:
┌─────────────────────────────────────────────────────────
│ 
│ [4068:4068:0203/082624:56314195:ERROR:browser_main_loop.cc(162)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
│ [4070:4070:0100/000000:56505802:ERROR:zygote_linux.cc(587)] write: Broken pipe
└─────────────────────────────────────────────────────────
```

In [build 8](https://travis-ci.org/a14n/dart-rational/builds/49287140) :

```
Detailed results of test suite rational_browser_test.dart:
┌─────────────────────────────────────────────────────────
│ 
│ [4078:4078:0203/083012:84333562:ERROR:browser_main_loop.cc(162)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
│ [4086:4086:0100/000000:84513896:ERROR:zygote_linux.cc(587)] write: Broken pipe
└─────────────────────────────────────────────────────────
```

In [build 9](https://travis-ci.org/a14n/dart-rational/builds/49287669):

```
Detailed results of test suite rational_test.dart:
┌─────────────────────────────────────────────────
│ 
│ Cannot create link, path = '/home/travis/build/a14n/dart-rational/packages/unittest' (OS Error: No such file or directory, errno = 2)
└─────────────────────────────────────────────────
Test suite passed: bigint_test.dart
Test suite failed: rational_browser_test.dart
Detailed results of test suite rational_browser_test.dart:
┌─────────────────────────────────────────────────────────
│ The test did not complete in less than 240 seconds. It was aborted.
└─────────────────────────────────────────────────────────
```

As you can see the tests are really unstable although the code base is the same.

About the timeout error: I face a similar behaviour in Dartium where the loading icon does not disappear.

@nicolasgarnier : Could you please provide some help ?

**Comment by nicolasgarnier** [comment]
I'm investigating. definitely something is wrong with the test runner. PS: you can run it locally (not through Travis) by:
 - Install Content Shell on your machine
 - Run `pub global activate test_runner`
 - Run `run_tests -c` from your project root

But I get the same issue (test not completing in 240 sec)

However if I run manually what the browser test runner is supposed to do things run fine:

    # run the test runner and kill it before completion so that temporary files are kept (will add an option to do that later)
    pub serve tests
    content_shell --args --dump-render-tree --disable-gpu http://localhost:8080/__test_runner/rational_browser_test.html

The output is correct and content shell quits almost instantly with:
```
#READY
Content-Type: text/plain
PASS
1	PASS	Expectation: string validation.
2	PASS	Expectation: valid js int.
3	PASS	Expectation: toString().
4	PASS	Expectation: operator ==(BigInt other).
5	PASS	Expectation: compareTo(BigInt other).
6	PASS	Expectation: operator +(BigInt other).
7	PASS	Expectation: operator -(BigInt other).
8	PASS	Expectation: operator *(BigInt other).
9	PASS	Expectation: operator %(BigInt other).
10	PASS	Expectation: operator ~/(BigInt other).
11	PASS	Expectation: operator -().
12	PASS	Expectation: string validation.
13	PASS	Expectation: parse scientific notation.
14	PASS	Expectation: get isInteger.
15	PASS	Expectation: operator ==(Rational other).
16	PASS	Expectation: toDecimalString().
17	PASS	Expectation: compareTo(Rational other).
18	PASS	Expectation: operator +(Rational other).
19	PASS	Expectation: operator -(Rational other).
20	PASS	Expectation: operator *(Rational other).
21	PASS	Expectation: operator %(Rational other).
22	PASS	Expectation: operator /(Rational other).
23	PASS	Expectation: operator ~/(Rational other).
24	PASS	Expectation: operator -().
25	PASS	Expectation: remainder(Rational other).
26	PASS	Expectation: operator <(Rational other).
27	PASS	Expectation: operator <=(Rational other).
28	PASS	Expectation: operator >(Rational other).
29	PASS	Expectation: operator >=(Rational other).
30	PASS	Expectation: get isNaN.
31	PASS	Expectation: get isNegative.
32	PASS	Expectation: get isInfinite.
33	PASS	Expectation: abs().
34	PASS	Expectation: signum.
35	PASS	Expectation: floor().
36	PASS	Expectation: ceil().
37	PASS	Expectation: round().
38	PASS	Expectation: truncate().
39	PASS	Expectation: clamp(Rational lowerLimit, Rational upperLimit).
40	PASS	Expectation: toInt().
41	PASS	Expectation: toDouble().
42	PASS	Expectation: toStringAsFixed(int fractionDigits).
43	PASS	Expectation: toStringAsExponential(int fractionDigits).
44	PASS	Expectation: toStringAsPrecision(int precision).
45	PASS	Expectation: hasFinitePrecision.
46	PASS	Expectation: precision.
47	PASS	Expectation: scale.
All 47 tests passed
#EOF
#EOF
#EOF
```

So nothing is wrong with your test nor with the technique used by the test runner (in theory). I'm investigating further. Will let you know as soon as I learn more...

**Comment by nicolasgarnier** [comment]
OK you can fix everything by running "pub get" before the test runner...

I'm investigating why this issue is happening but I think it's because multiple instances of `pub run` and `pub serve` are being ran in parallel - once for each test with a max of the number of available virtual processors - and if `pub get` has not been ran previously then they basically run `pub get` and it seems that running it multiple time in parallel makes it fail with errors like `Cannot create link, path = '/Users/nivco/Downloads/dart-rational-content_shell 6/packages/matcher' (OS Error: No such file or directory, errno = 2)` etc... which is kinda to be expected.

Best is that you run `pub get` explicitly first then the test runner. Let me know if that fixes things for you. I'll add a protection in the test runner to make it more stable. For instance I'll check if pubspec.lock exists and if not I'll run `pub get` before running any tests.

**Comment by nicolasgarnier** [comment]
I should also still show the output of the browser test (and not wait 240 sec) if an error has happened... I'll see if there was actually any output in this case as, maybe, `pub serve` was just hanging...

**Comment by a14n** [comment]
Argg ! Sorry about forgetting the `pub get` in my test :-(

I just fixed my [install script](https://github.com/a14n/dart-rational/blob/1e2f597169453f579ab9de3b824993c5682245d4/.travis.yml#L6) and run some builds.

[build 10](https://travis-ci.org/a14n/dart-rational/builds/49323225) :
```
Detailed results of test suite rational_browser_test.dart:
┌─────────────────────────────────────────────────────────
│ 
│ [4072:4072:0203/144041:82189213:ERROR:browser_main_loop.cc(162)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
│ [4084:4084:0100/000000:82426745:ERROR:zygote_linux.cc(587)] write: Broken pipe
└─────────────────────────────────────────────────────────
```

[build 11](https://travis-ci.org/a14n/dart-rational/builds/49323851):
```
Detailed results of test suite rational_browser_test.dart:
┌─────────────────────────────────────────────────────────
│ 
│ [4084:4084:0203/144517:58647392:ERROR:browser_main_loop.cc(162)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
│ [4098:4098:0100/000000:58883537:ERROR:zygote_linux.cc(587)] write: Broken pipe
└─────────────────────────────────────────────────────────
```

[build 12](https://travis-ci.org/a14n/dart-rational/builds/49324414):
```
Detailed results of test suite rational_browser_test.dart:
┌─────────────────────────────────────────────────────────
│ 
│ [4079:4079:0203/144928:62767921:ERROR:browser_main_loop.cc(162)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
│ [4091:4091:0100/000000:63023262:ERROR:zygote_linux.cc(587)] write: Broken pipe
└─────────────────────────────────────────────────────────
```

Now the error seems constant :) but I will trigger some other builds to know if the build can go further.

**Comment by nicolasgarnier** [comment]
Mhh let me investigate that as well....

**Comment by nicolasgarnier** [comment]
Ah yes I think I faced this error as well when writing the Docker container for the test runner (see: https://github.com/google/test_runner.dart/blob/master/docker/test.sh).

Basically you'r missing a Display for content_shell to work. For some reason Content Shell still needs a display even though it's running headlessly.

You need to make sure you have Xvfb installed on the machine (`apt-get xvfb` if it's not there) and then execute the test runner with:

    # Run the Test Runner and display results.
    xvfb-run -s '-screen 0 1024x768x24' run_tests -c

This should work too but I haven't tried:

    xvfb-run -s '-screen 0 1024x768x24' pub global run test_runner -c

**Comment by nicolasgarnier** [comment]
Let me know if this works :)

**Comment by a14n** [comment]
[You did it](https://travis-ci.org/a14n/dart-rational/builds/49331662) \o/

Thanks for your help. I still need to update this PR to reflect the changes I made in the tests.

**Comment by nicolasgarnier** [comment]
Awesome! I should also probably add an option to disable ANSI output (which I already do for Windows support) because the console line re-write is not supported in this case it would look nicer with the Windows Console style output.

**Comment by a14n** [comment]
@nicolasgarnier: done via c17deb6

**Comment by BanzaiMan** [comment]
@a14n Do you want to add specs for this?

**Comment by a14n** [comment]
@BanzaiMan no. The PR is basically about installing `content_shell` in the PATH and I don't see anything interesting to add in the spec.

Moreover would it be possible to push this PR on staging for a test ?

**Comment by BanzaiMan** [comment]
Deployed.

**Comment by sethladd** [comment]
Thanks!

**Comment by a14n** [comment]
Bad news :-( . I just run [a build](https://travis-ci.org/a14n/dart-rational/builds/49651190) and it fails to complete the _setup_ stage. I don't really understand why :-/ It blocks between [the line 52 and 55](https://github.com/travis-ci/travis-build/blob/20a76662eecd322e1b3ebb3218b9c48fdb40b0b0/lib/travis/build/script/dart.rb#L52-L55).

@BanzaiMan any idea ?

**Comment by a14n** [comment]
From the [detailed logs](https://s3.amazonaws.com/archive.travis-ci.org/jobs/49651192/log.txt) I see more things. I will have a deeper look.

**Comment by a14n** [comment]
@nicolasgarnier it look like the error faced at https://github.com/travis-ci/travis-build/pull/377#issuecomment-72614387 for [build #7](https://travis-ci.org/a14n/dart-rational/builds/49285682) is still underlying. I face it for may last 2 builds. Any idea ?

>  The test did not complete in 0:04:00.000000. It was aborted.

@BanzaiMan actually the log displayed on the web is mixed. The _Content Shell install_ fold appears [in the middle of the log at L553](https://travis-ci.org/a14n/dart-rational/builds/49651190#L553). Really strange.

**Comment by nicolasgarnier** [comment]
Actually the timeout errors were because of the missing `pub get` and because `pub run` and `pub serve` were conflictingly running a `pub get` in parallel... But since you run `pub get` before and since we're not using `pub run` anymore that can't happen... I'm having a look but it might be something that just shows in this environment :/ let me try to publish a new version of the test runner that would display what the underlying error is (lets hope something was printed to stdout/err :D). I'll let you know and you can re-run your tests and maybe the error will tell us more.

**Comment by a14n** [comment]
@nicolasgarnier my bad. I had a bad link in my test.html. After [having fixed it](https://github.com/a14n/dart-rational/compare/2b2f58001b03...1894435a6082) the build is ok.

**Comment by a14n** [comment]
@nicolasgarnier However it would be great to detect those kinds of error and to avoid this timeout error which is not easy to understand.

**Comment by a14n** [comment]
@BanzaiMan The logs on the build are still mixed and do not correspond to the detailed logs you can download. See for instance [this build #26](https://travis-ci.org/a14n/dart-rational/builds/49661437) and its [log details](https://s3.amazonaws.com/archive.travis-ci.org/jobs/49661438/log.txt).

**Comment by nicolasgarnier** [comment]
@a14n I agree although as per my investigation it seems that in this case content_shell just waits, prints #READY and wait forever without exiting... :/ Even the 404 errors don't get printed to the JS console. So there is not much I can do at this points from the test runner unfortunately... Not sure what causes content_shell not too exit though... Maybe something to do with test_controller.js. I'm having a look to see if there is any thing I can do.

**Comment by nicolasgarnier** [comment]
@a14n I think I've identified (and fixed) the "hanging" issue: https://github.com/dart-lang/unittest/pull/3

content_shell never triggers document.readyState == "loaded" but uses "complete" instead and there was a special case for when no tests are being ran in the page which used this.

**Comment by BanzaiMan** [comment]
Sorry, I couldn't keep up. Is there something you guys need me to do? I can spin up a debug VM, if you wan to investigate further. support@travis-ci.com

**Comment by a14n** [comment]
@nicolasgarnier I just tested the _hanging_ issue and your fix is ok. I now get a message:

```
Running all tests...
Test suite passed: rational_test.dart
Test suite passed: bigint_test.dart
Test suite failed: rational_browser_test.dart
Detailed results of test suite rational_browser_test.dart:
┌─────────────────────────────────────────────────────────
│ Loading and running tests
└─────────────────────────────────────────────────────────
Summary: 1 TEST SUITE(S) FAILED. 2 TEST SUITE(S) PASSED.
```

**Comment by a14n** [comment]
@BanzaiMan I think I found the issue about the mixing logs on the web page. In the [full logs](https://s3.amazonaws.com/archive.travis-ci.org/jobs/49707699/log.txt) the folds only contain the first word. For instance `travis_fold:start:Content` for `sh.fold 'Content Shell dependencies install'`. I wasn't aware that the `sh.fold` parameter shouldn't contain spaces. I will send a new PR to fix that.

**Comment by a14n** [comment]
The PR #380 should fix the issue.

**Pull request merged**
