### PR TITLE
update default D compiler (dmd) version to new 2.067 release

### PR DESCRIPTION
**Pull request by Extrawurst**

### CODE REVIEW

**Comment by Extrawurst** [comment]
oh just saw i am supposed to mention a few people here to attract the right guys: @MartinNowak, @klickverbot and @ibuclaw

**Comment by MartinNowak** [comment]
There is https://github.com/travis-ci/travis-ci/issues/3472 and you can already explicitly use `dmd-2.067.0`.

**Comment by Extrawurst** [comment]
@MartinNowak yeah but there is no PR in the other issue. i just thought default is supposed to be up to date, think it is documented as such

**Comment by nomad-software** [comment]
Yes that was my understanding. Just using:
```
language: d
```
should use the latest D compiler.

**Comment by MartinNowak** [comment]
I want a LATEST file for all compilers, so that `dmd`, `ldc`, and `gdc` can be used without specifying a version and it's no longer necessary to update the tracis-ci build scripts.

**Comment by MartinNowak** [comment]
Please close this in favor of #418.

**Comment by Extrawurst** [comment]
sure thing

**Pull request closed without merging**
