### PR TITLE
Add ensure_path_components appliance

### PR DESCRIPTION
**Pull request by BanzaiMan**
This ensures that certain paths are universally present in `$PATH`

Resolves https://github.com/travis-ci/travis-ci/issues/8890.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Tested: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/jobs/675918#L484

**Comment by danez** [comment]
When will the change be pushed? Still not working for me: https://travis-ci.org/researchgate/react-fast-highlight/jobs/316007276

**Comment by BanzaiMan** [comment]
It was, but I broke it again. We’ll deploy #1276 tomorrow.

**Comment by BanzaiMan** [comment]
@danez It's fixed now. Please restart affected builds. Thanks for reporting!

**Comment by danez** [comment]
Thanks for fixing, works fine now again.

**Pull request merged**
