### PR TITLE
Switch go version management to gimme

### PR DESCRIPTION
**Pull request by meatballhat**
This implementation aims to be independent of build env updates, although once gimme is shipped with the build image(s) we can then remove the presence check + download.  The disabling of gvm was required in order to have the correct go version activated, which I'm guessing will mean we may have to remove gvm entirely from the build env as well.

It's worth noting that the aliasing logic changes with this PR such that point releases such as `1.0` and `1.3` are now left alone rather than being "upgraded" to `1.0.3` and `1.3.3`, respectively.  The reasoning here is that such point releases are legitimate binary releases, whereas version `1.2` will still be "upgraded" to `1.2.2` as there is no `1.2` binary release available (at least in the well-known download locations).

Example build in staging: https://staging.travis-ci.org/travis-repos/go-test-staging/builds/405600

### CODE REVIEW

**Comment by joshk** [comment]
Does this allow for Go tip?

**Comment by meatballhat** [comment]
yep, tip is explicitly handled in gimme

**Comment by meatballhat** [comment]
@joshk specifically, here: https://github.com/meatballhat/gimme/blob/de1e10e1b6ab5a90239d5b0408859f82b88d85b3/gimme#L146

**Comment by joshk** [comment]
HUZZAH! :+1:

**Comment by meatballhat** [comment]
most recent staging build: https://staging.travis-ci.org/travis-repos/go-test-staging/builds/405657

**Comment by BanzaiMan** [comment]
OMG!

**Pull request merged**
