### PR TITLE
Dart support

### PR DESCRIPTION
**Pull request by a14n**
This will add support for [Dart](https://www.dartlang.org/).

```yaml
language: dart
```

You can provide the version to use with the `dart` property. `stable` is the default and you can use either `dev` or a version number.

If the project contains a `pubspec.yaml` file then `pub get` is launch.

Finally the script run `dart test/all_test.dart` if `test/all_test.dart` exists.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Is this ready for merge? (It's not live on staging now, but if you need further testing, let me know.)

**Comment by a14n** [comment]
The only last thing I hadn't test with success was the matrix expansion ([you pointed that it was not deployed](https://github.com/travis-ci/travis-build/pull/357#issuecomment-68443452)). Otherwise, it looks good to me.

**Comment by BanzaiMan** [comment]
@a14n OK. I'll work on the blog post, and when it's ready, I'll merge this and deploy to production. Once that's done, we can work on the matrix expansion.

**Comment by BanzaiMan** [comment]
@a14n Could you address the fold issue I mentioned earlier? Also, could you work on the matrix expansion PR, much like https://github.com/travis-ci/travis-core/pull/416?

I'm hoping to get this out next week.

**Comment by a14n** [comment]
@BanzaiMan done for fold (see 532854a77ef8c09d2998c8000d134c9999faadee). Let me know if it is what you expected.

See also https://github.com/travis-ci/travis-core/pull/422 for matrix expansion.

**Comment by nicolasgarnier** [comment]
Hey @a14n, I came up with instructions on how to install content_shell on Ubuntu if you're interested :)
Here are the instructions:

For Ubuntu Trusty:
  - Enable multiverse packages: `echo "deb http://gce_debian_mirror.storage.googleapis.com wheezy contrib non-free" >> /etc/apt/sources.list && echo "deb http://gce_debian_mirror.storage.googleapis.com wheezy-updates contrib non-free" >> /etc/apt/sources.list && apt-get update`
 - Install these dependencies: `apt-get install chromium browser ttf-kochi-gothic ttf-kochi-mincho ttf-mscorefonts-installer ttf-indic-fonts ttf-dejavu-core ttf-indic-fonts-core fonts-thai-tlwg`
 - Trick to get libudev0: `ln -sf /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0`

If you are using a different version than trusty you'll need to tweak enabling the multiverse packages and maybe you won't need the "Trick to get libudev0". Also since this is an automated build and you can't interact to accept the Microsoft EULA for the fonts you should add:

 - Pre accepts the mscorefonts EULA: `echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections`


If it helps or if you are curious, I created a Docker image that has all the test runner dependencies installed. Here the the latest version which is based on debian:wheezy https://github.com/google/test_runner.dart/blob/master/docker/Dockerfile

I had a previous version based on ubuntu:trusty https://github.com/google/test_runner.dart/blob/6b4439af2e250a9b0fcc57bd9a14f0de210798ff/docker/Dockerfile

**Comment by a14n** [comment]
@nicolasgarnier Thanks for the instructions. Given that this PR is close to be merged I will open a new PR to add content_shell. However it seems that the ubuntu version is not _trusty_, it's _precise_. Does your instructions work also on _precise_ ?

**Comment by nicolasgarnier** [comment]
There is a slight variation for precise. It's better actually since you can install `libudev0` using `apt-get` you don't have to do the `ln -s` trick.

I've written all instructions [here](/google/test_runner.dart/blob/master/CONTENT_SHELL_INSTALL_INSTRUCTIONS.md)

But in your case you basically do:

    # Enable Multiverse Packages:
    echo "deb http://gce_debian_mirror.storage.googleapis.com precise contrib non-free" >> /etc/apt/sources.list
    echo "deb http://gce_debian_mirror.storage.googleapis.com precise-updates contrib non-free" >> /etc/apt/sources.list
    apt-get update
    
    # Pre-accepts MSFT Fonts EULA:
    echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
    
    # Install all dependencies:
    apt-get install chromium-browser libudev0 ttf-kochi-gothic ttf-kochi-mincho ttf-mscorefonts-installer ttf-indic-fonts ttf-dejavu-core ttf-indic-fonts-core fonts-thai-tlwg

Then you can dowanload the content_shell zip file, unzip it and add it to the PATH. For instance:

    mkdir /usr/local/content_shell
    cd /usr/local/content_shell
    wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/dartium/content_shell-linux-x64-release.zip
    unzip content_shell-linux-x64-release.zip
    rm content_shell-linux-x64-release.zip
    mv $(ls) latest
    export PATH=/usr/local/content_shell/latest:$PATH

**Comment by BanzaiMan** [comment]
Is further testing necessary before deploying this?

**Comment by a14n** [comment]
No, it's ready to deploy.

I will open a new PR to allow in-browser testing. It will be easier to track.

**Comment by nicolasgarnier** [comment]
By the way if there are any docs on how to setup Travis on a Dart project I'll be happy to point to it from the Dart Test Runner docs. If there are no specific docs for it I'll probably add a section on how to use Travis on a Dart project in the Dart Test Runner's docs.

Anyways thanks @a14n for working on this! :)

**Comment by a14n** [comment]
@nicolasgarnier there are [several PRs for Dart support](https://github.com/travis-ci/travis-build/pull/357#issuecomment-66928355). For the documentation it's https://github.com/travis-ci/docs-travis-ci-com/pull/159

**Comment by bgourlie** [comment]
@a14n Did you create the issue to track in-browser testing?  I'd like to subscribe to it.  

Aside from that, any idea when this PR will land?

**Comment by a14n** [comment]
@bgourlie no issue for in-browser testing.

About the merge of this current PR I'm waiting eagerly for the merge but I don't really know what is blocking it.

**Comment by a14n** [comment]
\o/

**Comment by BanzaiMan** [comment]
I've deployed this, but hub still needs to be merged and deployed. That'll probably have to wait until tomorrow (so that `dart` can expand as a matrix axis).

**Comment by BanzaiMan** [comment]
To be announced via: https://github.com/travis-ci/blog-travis-ci-com/pull/58

**Comment by a14n** [comment]
Awesome. Thanks @BanzaiMan.

Let me know when it's completed.

Reminder: there are other PRs related to the Dart support pointed in [a previous comment](https://github.com/travis-ci/travis-build/pull/357#issuecomment-66928355).

**Comment by devoncarew** [comment]
Awesome - really excite to see this land!

**Comment by a14n** [comment]
@devoncarew actually it's already there :D See https://travis-ci.org/a14n/dart-metrics

The only limitation **until tomorrow** is that you can not build _stable_ AND _dev_.

Working:

```yaml
language: dart
```

Working:

```yaml
language: dart
dart: dev
```

Not working but should be ok tomorrow:

```yaml
language: dart
dart:
  - stable
  - dev
```

**Comment by sethladd** [comment]
Woohoo!

**Comment by a14n** [comment]
@BanzaiMan I just made a build and there seems to be no expansion for multiple dart versions (see https://travis-ci.org/a14n/dart-metrics/builds/48728554). According to your last message it should have been activated yesterday. Was there a problem ?

**Comment by BanzaiMan** [comment]
Hmm. This is weird. Correct code should be deployed to enable matrix expansion. I'll take a deeper look.

Sorry for the inconvenience.

**Comment by BanzaiMan** [comment]
I found the issue. I'll deploy the fix on Monday.

**Comment by a14n** [comment]
Thanks for having take a look. I'll try again on monday.

**Comment by a14n** [comment]
BTW: https://github.com/travis-ci/travis-ci/issues/1733 can now be closed.

**Comment by BanzaiMan** [comment]
Dart matrix support is now live: https://travis-ci.org/BanzaiMan/travis_production_test/builds/49182648

**Comment by a14n** [comment]
It works for me too. Thanks :)

**Comment by bgourlie** [comment]
@a14n Are you still planning on implementing browser tests?  If so, is there anything you need help with?

**Comment by BanzaiMan** [comment]
@bgourlie May I suggest opening a separate issue about that? Otherwise I'll have to lock this issue. ;-)

**Comment by bgourlie** [comment]
@BanzaiMan Sorry about all the noise.  I'd open an issue but this repository doesn't seem to allow me to create issues.  The issues link is non-existent.

**Comment by BanzaiMan** [comment]
@bgourlie Sorry about that. Please use https://github.com/travis-ci/travis-ci/issues/new.

**Comment by bgourlie** [comment]
Thanks!

@a14n https://github.com/travis-ci/travis-ci/issues/3162

**Pull request merged**
