### PR TITLE
[Smalltalk] Raise max real-time priority temporarily

### PR DESCRIPTION
**Pull request by fniephaus**
Hi @BanzaiMan,

This compiles and runs a program that raises the max RT priority limit temporarily. This is necessary to run latest OpenSmalltalk VMs on Travis CI. The source code of the program is inline. It basically just uses `prlimit()` to raise the limit as described [here](https://linux.die.net/man/2/setrlimit).

[Here's a build](https://travis-ci.org/fniephaus/travis-experiments/builds/173689894) that shows that it works as intended.

Please do not push straight to production. I'd like to make sure it works on staging first.

Many thanks,
Fabio

Related: https://github.com/travis-ci/travis-ci/issues/6815

### CODE REVIEW

**Comment by fniephaus** [comment]
*friendly ping*

**Comment by BanzaiMan** [comment]
Hello. Do you have a repo set up in staging? https://staging.travis-ci.org/ If not, please set one up. Then we can coordinate testing.

**Comment by fniephaus** [comment]
Yep, [here you go](https://staging.travis-ci.org/fniephaus/smalltalkCI-staging/). I will push some code as soon as you tell me to :)

**Comment by BanzaiMan** [comment]
@fniephaus This has been deployed.

**Comment by fniephaus** [comment]
Thanks. Now waiting for staging to start a build. BTW, @timfel says hi 😃

**Comment by BanzaiMan** [comment]
👋  @timfel!!

**Comment by fniephaus** [comment]
Ok, so [it's failing](https://staging.travis-ci.org/fniephaus/smalltalkCI-staging/builds/525618#L199) because it can't find the file. I just realized that the file was create in some working dir but not in the working dir of the bash. Also, I saw that there is a template mechanism for these kind of use cases. I've pushed https://github.com/travis-ci/travis-build/pull/879/commits/04ac3381226fe3b1ad4f7d9ec592eb462fdac43e. Please have a look and if you're ok with it, please deploy to staging. Thanks!

**Comment by BanzaiMan** [comment]
Deployed.

**Comment by fniephaus** [comment]
Thanks! I'm currently looking for the reason why the [operation was not permitted](https://staging.travis-ci.org/fniephaus/smalltalkCI-staging/builds/525626#L148). The same script works fine [here](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/0e510b13177d52165e689d78414c6870b2a62196/.travis_test.sh#L10-L12). Not sure if the double [`$$`](https://github.com/fniephaus/travis-build/blob/e0ea02c1fbd6253f27ad5cfbceed0a42ff5c2912/lib/travis/build/script/smalltalk.rb#L243) are being escaped, it doesn't look like it at least.
Don't expect you to have time to look into this, but if you do it'd be much appreciated.

**Comment by fniephaus** [comment]
Ok, interestingly, [it works](https://staging.travis-ci.org/fniephaus/smalltalkCI-staging/builds/525628) when `sudo: required`. This is weird, because I'm able to run `sudo apt-get ...`, but not the `prlimit` tool. Correct me if I'm wrong, but it looks like prlimit is not supported by Docker, right? 😢

**Comment by BanzaiMan** [comment]
@fniephaus I am not familiar, but I suppose that might be a problem.

I can reproduce the problem on my Mac running Docker:

```sh-session
$ docker run --rm -it quay.io/travisci/travis-ruby su - travis
travis@5a4f87f9c679:~$ wget https://raw.githubusercontent.com/fniephaus/travis-build/e0ea02c1fbd6253f27ad5cfbceed0a42ff5c2912/lib/travis/build/templates/smalltalk/set_rtprio_limit.c
--2016-11-21 21:31:00--  https://raw.githubusercontent.com/fniephaus/travis-build/e0ea02c1fbd6253f27ad5cfbceed0a42ff5c2912/lib/travis/build/templates/smalltalk/set_rtprio_limit.c
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.56.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.56.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1151 (1.1K) [text/plain]
Saving to: `set_rtprio_limit.c'

100%[==================================================================================================================================================================================================================================================================================>] 1,151       --.-K/s   in 0s

2016-11-21 21:31:00 (147 MB/s) - `set_rtprio_limit.c' saved [1151/1151]

travis@5a4f87f9c679:~$ gcc -o set_rtprio_limit set_rtprio_limit.c
travis@5a4f87f9c679:~$ ./set_rtprio_limit  $$
prlimit-rtprio-1: Operation not permitted
```

**Comment by timfel** [comment]
I think you have to start the docker instance itself with - - ulimit
rtprio=2 to allow the guest to raise the limit.

Hiro Asari <notifications@github.com> schrieb am Mo., 21. Nov. 2016, 22:32:

**Comment by fniephaus** [comment]
Yep, I've also noticed that it doesn't work locally with Docker on my Mac.
Starting a container with `docker run --ulimit rtprio=2:2 ...` works, but I'm afraid this is something we can't change with regard to Travis, right?

**Comment by BanzaiMan** [comment]
> I'm afraid this is something we can't change with regard to Travis, right?

Affirmative. This is not easily achievable with the current infrastructure.

**Comment by fniephaus** [comment]
Thanks for letting us test this in staging, but I guess we need to find another way to run our VMs on Docker.

**Pull request closed without merging**
