### PR TITLE
[julia] Assertions to avoid masked failures

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes the problems identified in https://github.com/travis-ci/travis-build/pull/1450#issuecomment-424808189

cc: @travis-ci/julia-maintainers @ararslan @NHDaly

### CODE REVIEW

**Comment by NHDaly** [comment]
Thanks Simon!

**Comment by simonbyrne** [comment]
@ararslan any chance you could try this out on the repo you were having the problem with?

**Comment by ararslan** [comment]
I've opened a PR on the repo updating it to use this, but I'm not sure what the cause of the earlier failure was that got masked.

**Comment by simonbyrne** [comment]
Well, you could checking that `@test 1==2` still causes a test failure?

**Comment by ararslan** [comment]
https://github.com/JuliaLang/Example.jl/pull/37

**Comment by simonbyrne** [comment]
Looks good then.

**Comment by simonbyrne** [comment]
From @ararslan  
> My only gripe with this now is that it shows up as build errors (designated with ❗️) rather than build failures (designated with ❌).

https://travis-ci.org/JuliaLang/Example.jl/builds/451103142?utm_source=github_status&utm_medium=notification

@BanzaiMan: I'm guessing to fix that we would need to move it to `after_after_success`?

**Comment by iamed2** [comment]
Yes that is a big annoyance. Also, will failures in coverage submission now cause the build to fail?

**Comment by simonbyrne** [comment]
Yes, that is actually a very good argument for moving it.

**Comment by ararslan** [comment]
Unless that's fixed soon, can we revert this in the meantime?

**Comment by simonbyrne** [comment]
Well, the previous behaviour was worse IMHO

**Comment by simonbyrne** [comment]
just don't use coverage for now

**Comment by ararslan** [comment]
Does this not affect builds that don't have coverage submission at the top level? It seems like it would because of the `assert`s.

**Comment by ararslan** [comment]
It does, see https://travis-ci.org/JuliaLang/Example.jl/builds/451118887?utm_source=github_status&utm_medium=notification

**Pull request merged**
