### PR TITLE
Allow t6 file extension for perl6 tests

### PR DESCRIPTION
**Pull request by ugexe**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
@paultcochrane @hoelzro @ugexe @tony-

Opinions, please.

**Comment by tony-o** [comment]
(I'm also assuming you meant me and not @tony- )

**Comment by BanzaiMan** [comment]
@tony-o Oops! I did, indeed.

**Comment by BanzaiMan** [comment]
@ugexe Please open a docs update PR for https://docs.travis-ci.com/user/languages/perl6. Thanks!

**Pull request merged**
