### PR TITLE
Update NVM to version 0.31.6

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by ljharb** [comment]
@BanzaiMan it'd be great to get this in :-) includes LTS support.

**Comment by ljharb** [comment]
I've filed https://github.com/travis-ci/travis-cookbooks/pull/756 as well to update to v0.31.6 - @BanzaiMan, is this repo, or travis-cookbooks, the right place to update `nvm`?

@PeterDaveHello can you update this to v0.31.6?

**Comment by BanzaiMan** [comment]
@ljharb This is for on-demand updates; if this version is newer than the one on the image, `nvm` is updated _on the fly_. If it is not, it is a no-op.

**Comment by ljharb** [comment]
aha - then both PRs are good to update :-) after @PeterDaveHello updates this to v0.31.6, let's please merge this ASAP!

**Comment by PeterDaveHello** [comment]
Updated!

**Comment by keithamus** [comment]
Hey @BanzaiMan, no pressure or anything - take all the time you need and stuff, make sure to handle important life stuff first, but then maybe...

**Comment by GrahamCampbell** [comment]
Could be worse. I've been waiting over 18 months to get a new version of PHP 5.6 onto travis. Still nothing!

**Comment by keithamus** [comment]
Thanks @BanzaiMan!

**Pull request merged**
