### PR TITLE
Better checking for failures in our R scripts.

### PR DESCRIPTION
**Pull request by craigcitro**
We use inline R scripts for several steps (eg package installation), but don't
convert script failures into a nonzero exit status. This diff fixes this for
all `Rscript` calls.

PTAL @hadley and @cbarraford for the R/ruby bits, and then @BanzaiMan for the merge once they OK.

### CODE REVIEW

**Comment by hadley** [comment]
Did you consider setting the global error option to `q(status = 1)`?

**Comment by craigcitro** [comment]
that's a good idea -- it would mean that i could drop the various `tryCatch` blocks, right?

i'd still need to do the manual checking on package installs, since `install.packages` doesn't signal an error if something goes wrong. (maybe i could also do `options(warn = 2)`, but i suspect that would lead to other warnings on package install spuriously becoming errors.)

**Comment by hadley** [comment]
Maybe littler already has the capability to do that? Worth checking with @eddelbuettel first

**Comment by eddelbuettel** [comment]
littler lets you do what R already offers:

```{.bash}
edd@max:~$ r -e'q("no", 0)' && echo No Error                                                                                                                                                                         
No Error
edd@max:~$ r -e'q("no", 42)' || echo "Error $?"
Error 42
edd@max:~$ 
```

**Comment by craigcitro** [comment]
@eddelbuettel but in particular, `littler` doesn't change the R defaults for things like setting an exit status on command error?

**Comment by craigcitro** [comment]
@hadley the other question is about messaging: if i set the global `error` option, i don't get my hands on the error (to print it first), unless i'm missing something. (is there a simple way to ask R for "last error"?)

**Comment by craigcitro** [comment]
@hadley any objections to this going in as-is, with the caveat that we may want to clean it up later?

(i know @BanzaiMan was looking to merge some things early Monday ...)

**Comment by BanzaiMan** [comment]
Ping me when you are satisfied with this PR.

**Comment by hadley** [comment]
LGTM, although I wish `install.packages()` failed with an error.

**Comment by craigcitro** [comment]
@hadley me too.

@BanzaiMan i think we're good to go. (this works, there may be a cleaner version later.)

**Pull request merged**
