### PR TITLE
Clone repo with tarball

### PR DESCRIPTION
**Pull request by BanzaiMan**
Use tarball strategy to clone repo. The PR build will fail. See https://github.com/travis-ci/travis-ci/issues/3923

### CODE REVIEW

**Comment by joshk** [comment]
is this for testing purpose?

**Comment by BanzaiMan** [comment]
@joshk confirm. (I've only seen this in a user report, so I'm reproducing it here.)

**Comment by joshk** [comment]
Coolio, is this from Zendesk?

**Comment by BanzaiMan** [comment]
Whoa. It did not fail. Totally unexpected.

@joshk Confirm. Perhaps the error is elsewhere.

Closing this, since the experiment is over (in a disappointment).

**Comment by BanzaiMan** [comment]
Perhaps this failed because this is a public repository. :-/

I'll have to test it on a private repo.

**Pull request closed without merging**
