### PR TITLE
Install Perl on demand

### PR DESCRIPTION
**Pull request by BanzaiMan**
🐪

### CODE REVIEW

**Comment by meatballhat** [comment]
\*ports to cookbooks\*

**Comment by meatballhat** [comment]
The namespace for the tarball appears to be `14.04`.  Could this be a wee bit more specific?  Perhaps `$(lsb_release -is | tr '[:upper:]' '[:lower:]')/$(lsb_release -rs)/$(arch)`, which would be `ubuntu/14.04/x86_64`?

**Comment by BanzaiMan** [comment]
Sure thing! We need to standardize paths (hierarchy and names) across all languages.

**Comment by meatballhat** [comment]
@BanzaiMan I'd love to get some standardization action going.  I'm assuming that anything that's dynamically linked will need to have distro and arch information, and namespacing by OS is cool.  This sounds related to the internal discussion of stacks, too, but then we're getting very Travis-specific.  Dunno.  Talking time.

**Comment by BanzaiMan** [comment]
Rebased to use the standard archive URL scheme, based on #539.

**Comment by BanzaiMan** [comment]
I've tested on staging this PR and the archiving process. It is ready to go, and I plan to deploy it next Monday.

**Pull request merged**
