### PR TITLE
WIP: Initial work on windows support for R

### PR DESCRIPTION
**Pull request by jimhester**
This is not complete, but I wanted to put something out there to work off of / discuss.

## Things still to be done

- [x] - Auto-detect the correct Rtools version based on (https://cran.r-project.org/bin/windows/Rtools/)
- [x] - Allow user override of Rtools version
- [x] - Do something about LaTeX and pandoc, R-appveyor apparently punts on this and removes Vignettes entirely.
- [x] - Package architectures, build one or both by default, probably also user configurable.
- [ ] - Writing documentation

## open questions
For @BanzaiMan or anyone else at Travis who can answer them.

1. Is there a staging area for Windows that we can use to test this?
2. How do we ensure we have sufficient privileges to run an executable installer?
3. What is the preferred method of running installers? Will the powershell command I used work or would you suggest an alternative.

cc @jeroen

### CODE REVIEW

**Comment by BanzaiMan** [comment]
@jimhester Use https://staging.travis-ci.com to set up a repo. When I have a chance, this will be deployed there.

**Comment by jimhester** [comment]
Sorry for the delay @BanzaiMan, I created a repository at https://staging.travis-ci.com/jimhester/travistest2, so it would great to have this deployed there to see what if anything breaks.

**Comment by BanzaiMan** [comment]
This has been deployed to https://staging.travis-ci.com.

**Comment by BanzaiMan** [comment]
This has been deployed to https://staging.travis-ci.com again.

**Comment by jimhester** [comment]
Hi, sorry for the delay, I am now trying to work on this again, but it looks like maybe code from this PR is no longer deployed to staging? Also there seems to be some issue with the build logs on staging (e.g. https://staging.travis-ci.com/jimhester/travistest2/jobs/245529)

**Comment by BanzaiMan** [comment]
This has been deployed to https://staging.travis-ci.com/. I apologize in advance that we may have to be deployed over without notice.

**Comment by hol430** [comment]
Hi all - just wondering what the status is on this, and if there are any plans to get it going again. I'm happy to help if I can.

**Comment by jeroen** [comment]
I don't think this is maintained. We have converged to appveyor and GHA for Windows.

**Pull request closed without merging**
