### PR TITLE
Upgrade Go versions

### PR DESCRIPTION
**Pull request by itchyny**
Regarding the security upgrade: https://github.com/golang/go/issues/23672
Depends on https://github.com/travis-ci/gimme/pull/124

### CODE REVIEW

**Comment by itchyny** [comment]
Now blocked by https://github.com/travis-ci/gimme/pull/125.

**Comment by meatballhat** [comment]
@itchyny The rake tests should not be changed, fwiw, as the input is stubbed 👍

**Comment by itchyny** [comment]
Oops, thank you. I dropped the commit and force-pushed. I don't still understand how the two repositories are related though...

**Pull request merged**
