### PR TITLE
Alias should be set to 3.5.0, not 3.5

### PR DESCRIPTION
**Pull request by jimhester**
Fixes https://github.com/travis-ci/travis-ci/issues/9654

### CODE REVIEW

**Comment by jimhester** [comment]
I added an additional change updating the R oldrel to version to 3.4.4, which was not properly updated when 3.5 was released.

**Comment by jimhester** [comment]
@BanzaiMan does this look ok and can be merged? I believe the build failure is not due to changes in the PR.

**Comment by jeroen** [comment]
Looks good to me.

**Comment by joepvd** [comment]
Apologies for the wait. PR builds should behave better now.

**Pull request merged**
