### PR TITLE
Always install gimme

### PR DESCRIPTION
**Pull request by meatballhat**
and remove references to previous repo slug.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
@meatballhat I'm think the config option should be retained for uses on Enterprise.

**Comment by meatballhat** [comment]
@BanzaiMan Which config option, or what behavior should be retained?

**Comment by BanzaiMan** [comment]
@meatballhat I think I misspoke.

**Comment by BanzaiMan** [comment]
Tested: https://staging.travis-ci.org/meatballhat/yolo-octo-adventure/jobs/619359#L426

**Pull request merged**
