### PR TITLE
Add coverity's SSL cert when configuring addon

### PR DESCRIPTION
**Pull request by BanzaiMan**
Based on https://github.com/travis-ci/travis-ci/issues/6142#issuecomment-226054248

Resolves https://github.com/travis-ci/travis-ci/issues/6142.

### CODE REVIEW

**Comment by un1versal** [comment]
Really good :) 

Is this change live? If it is Ill look into reverting workaround asap.

**Comment by BanzaiMan** [comment]
It is live now.

**Comment by un1versal** [comment]
Sorry, and no ca-certificates need right?

**Comment by BanzaiMan** [comment]
Correct. Coverity Scan should work without the workaround in https://github.com/travis-ci/travis-ci/issues/6142#issuecomment-226054248.

**Comment by un1versal** [comment]
Thanks again, for looking into this so soon and replies :) Im sure its appreciated by all

have a good one.

**Pull request merged**
