### PR TITLE
Update dart.rb to sleep after xvfb start

### PR DESCRIPTION
**Pull request by a14n**
give xvfb some time to start

### CODE REVIEW

**Comment by a14n** [comment]
@kevmoo

**Comment by a14n** [comment]
This follow the snippet on https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI and could reduce issues with content shell.

**Comment by BanzaiMan** [comment]
In general, I think it is better to sleep until certain conditions are met.

Here, we want to actually check that the display is available.

We'd want something like:

```shell
t=0; sh -e /etc/init.d/xvfb start; until (xdpyinfo -display :99 &> /dev/null || test $t > 10); do sleep 1; let t=$t+1; done
```

(We can still merge this, if a constant sleep is sufficient for this use case.)

**Comment by kevmoo** [comment]
@BanzaiMan the bash is strong with you - WOW

**Comment by a14n** [comment]
Thanks for the tip. It could be worth to update https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI with that.

BTW there seems to be a little typo : `test $t > 10` vs. `test $t -gt 10`

```sh
t=0; sh -e /etc/init.d/xvfb start; until (xdpyinfo -display :99 &> /dev/null || test $t -gt 10); do sleep 1; let t=$t+1; done
```

**Comment by a14n** [comment]
PTAL

**Comment by BanzaiMan** [comment]
Ah, yes. `-gt` is more appropriate for integer comparison. (`>` worked for my simple case, but I suspect it's not great in general.)

**Comment by kevmoo** [comment]
LGTM!

**Comment by BanzaiMan** [comment]
sorry for the delay.

**Comment by a14n** [comment]
thanks :)

**Pull request merged**
