### PR TITLE
Dart revamp

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by kevmoo** [comment]
Thanks, @a14n !

Look okay, @BanzaiMan ?

**Comment by BanzaiMan** [comment]
This has been deployed to staging. Could you test it? If it goes well, we can merge and deploy later this week. Thank you!

**Comment by kevmoo** [comment]
I tried running with this and I'm getting a pile of pain

See https://staging.travis-ci.org/kevmoo/shelf/builds/559094

I'd expect each task to have a separate job – but no luck.

Also: just blank output.

Any ideas, @a14n ?

**Comment by BanzaiMan** [comment]
@kevmoo Ah, sorry about that. There was another component that needed to be deployed before `dart_task` could be recognized as a matrix dimension. This is done now. Please push a new commit to test. Thanks.

**Comment by kevmoo** [comment]
Looking waaaay better – https://staging.travis-ci.org/kevmoo/shelf/builds/559143

Still now output, though.

Going to try one more quick, too.

**Comment by BanzaiMan** [comment]
The log display issue is most likely due to our ongoing development. I suspect it'll get better in a few hours.

**Comment by kevmoo** [comment]
I wish there was a way to show the task on this page – https://staging.travis-ci.org/kevmoo/shelf/builds/559143 

...not sure if that's a feature request for travis or what...

**Comment by BanzaiMan** [comment]
The task display would be a separate PR for travis-web once we ship this.

**Comment by kevmoo** [comment]
https://staging.travis-ci.org/kevmoo/shelf/builds/559250

I'm trying to get the build matrix to work w/ `dart_task` and having no luck.

Help?

**Comment by a14n** [comment]
I think the issue is with staging state and not with this PR. I made a quick test some minutes ago and it was worked as intended.

**Comment by a14n** [comment]
https://staging.travis-ci.org/a14n/dart-rational/builds/559162

The build matrix was ok. There were some failing jobs but due to my codebase.

**Comment by kevmoo** [comment]
> The build matrix was ok. There were some failing jobs but due to my codebase.

I'm breaking with `allow_failures` in https://staging.travis-ci.org/kevmoo/shelf/builds/559250
 ...that's what I meant by matrix...

**Comment by a14n** [comment]
It looks like matrix expansion for `dart_task` has been removed from staging... @BanzaiMan can you confirm ?

**Comment by BanzaiMan** [comment]
@kevmoo @a14n it was. It's been fixed now.

**Comment by a14n** [comment]
@BanzaiMan thanks

Staging looks more stable now and my tests are ok ( @kevmoo I also test `allow_failures` with https://staging.travis-ci.org/a14n/dart-rational/ )

**Comment by BanzaiMan** [comment]
@a14n @kevmoo Would you like to perform any more test?

**Comment by a14n** [comment]
it's ok for me.

**Comment by kevmoo** [comment]
I'm a bit nervous.

I've been trying to run the existing Dart angular2 tests (some of our most complex) against staging without clear results.

See https://staging.travis-ci.org/kevmoo/angular2/

VS https://travis-ci.org/dart-lang/angular2

**Comment by BanzaiMan** [comment]
@kevmoo Looks like our messages crossed paths. We are having problems with staging at the moment, and we are looking into it. I'll hold off deploying until we resolve this and you have another look at your results.

**Comment by kevmoo** [comment]
Thank you!

**Comment by BanzaiMan** [comment]
@kevmoo OK. Staging is back. Please check your results.

**Comment by kevmoo** [comment]
Rerunning now - https://staging.travis-ci.org/kevmoo/angular2/builds/559295

**Comment by BanzaiMan** [comment]
@kevmoo Looks like your build needs some user input.

**Comment by kevmoo** [comment]
> @kevmoo Looks like your build needs some user input.

Yup. Which is weird. Because this "just works" on the stable branch. I wonder if the install content-shell logic that @nex3 moved around got broken some how...

**Comment by a14n** [comment]
The [`content_shell_dependencies_install` fold](https://github.com/a14n/travis-build/blob/07bd86e57e8bcd2832d77da45a681e34de879321/lib/travis/build/script/dart.rb#L54-L67) in which the user input occurs has not been changed in this PR. That's really strange. Perhaps something specific with staging ?

**Comment by BanzaiMan** [comment]
It is not clear to me why the difference manifests this way, but it appears that the production and staging have different Precise images. Production https://travis-ci.org/dart-lang/angular2/jobs/215658287#L23 vs Staging https://staging.travis-ci.org/kevmoo/angular2/jobs/559296#L23

**Comment by BanzaiMan** [comment]
We can roll it out to Production, test it quickly, and revert if the problem manifests there.

**Comment by BanzaiMan** [comment]
I tested the build script with the docker image (https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally) and the `apt-get` command does appear to go through.

If we cannot agree on how to deploy this, I will revert his, so that we can test more thoroughly.

**Comment by kevmoo** [comment]
@BanzaiMan If you want to roll the dice, I'm happy to try.

I can rerun https://travis-ci.org/dart-lang/angular2/builds/215658286 immediately to see if it stays green.

**Comment by kevmoo** [comment]
...are you going to be around for a while to do the rollback if things blow up?

**Comment by kevmoo** [comment]
We should also make sure we align with un-reverting the docs - https://github.com/travis-ci/docs-travis-ci-com/commits/gh-pages/user/languages/dart.md

**Comment by BanzaiMan** [comment]
@kevmoo OK. Let's try. I'll deploy around 17:30 UTC (12+ minutes from now).

**Comment by BanzaiMan** [comment]
@kevmoo Deployed to production.

**Comment by kevmoo** [comment]
Rerunning https://travis-ci.org/dart-lang/angular2/builds/215658286

**Comment by BanzaiMan** [comment]
https://travis-ci.org/dart-lang/angular2/jobs/215658287 Got past the dependency installation phase.

**Comment by kevmoo** [comment]
This makes me nervous: https://travis-ci.org/dart-lang/shelf/jobs/216033195

Where this works: https://staging.travis-ci.org/kevmoo/shelf/builds/559992

**Comment by BanzaiMan** [comment]
@kevmoo https://travis-ci.org/dart-lang/shelf/builds/216033193 seems to have incorrect matrix configuration. (It should have 30=6x5 jobs, but only shows 6.)

Could you try pushing a new commit to this branch?

**Comment by kevmoo** [comment]
@BanzaiMan - done

https://travis-ci.org/dart-lang/shelf/builds/216039265

🤞

**Comment by BanzaiMan** [comment]
Hmm. This is strange. I'll look into this.

**Comment by kevmoo** [comment]
Weird!

Same commit – https://staging.travis-ci.org/kevmoo/shelf/builds/560030

So staging is doing the matrix correctly. But it's not working on master. 😕

**Comment by a14n** [comment]
same here https://travis-ci.org/a14n/dart-rational/builds/216040112
no matrix expansion

**Comment by BanzaiMan** [comment]
Sorry. The closed source part had not been deployed to production yet. I did so now.

Please push another commit. Thank you for your patience!

**Comment by kevmoo** [comment]
Here we go again: https://travis-ci.org/dart-lang/shelf/builds/216042341

**Comment by a14n** [comment]
The result is ok for my test (https://travis-ci.org/a14n/dart-rational/builds/216041592)

**Comment by BanzaiMan** [comment]
Looks much better. 28=6x5+1-3 jobs in the matrix.

**Comment by kevmoo** [comment]
I think I did *this* one correctly -
https://travis-ci.org/dart-lang/shelf/builds/216043979

So far so good...

**Comment by BanzaiMan** [comment]
For showing `dart_task` in the build matrix page, you'd want something like this PR: https://github.com/travis-ci/travis-web/pull/339.

**Comment by kevmoo** [comment]
> For showing dart_task in the build matrix page, you'd want something like this PR: travis-ci/travis-web#339.

@BanzaiMan I'm happy to do this... should I?

Also – can we get the docs refreshed? https://github.com/travis-ci/docs-travis-ci-com/commits/gh-pages/user/languages/dart.md

**Comment by kevmoo** [comment]
This seems like an unrelated break - https://travis-ci.org/dart-lang/shelf/jobs/216043982

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/docs-travis-ci-com/pull/1066 for docs update.

**Comment by BanzaiMan** [comment]
@kevmoo https://travis-ci.org/dart-lang/shelf/jobs/216043982 shows a failure with `xvfb-run` command.

**Comment by kevmoo** [comment]
@BanzaiMan https://github.com/travis-ci/travis-web/pull/1024 😄

**Pull request merged**
