### PR TITLE
Add Haxe Windows support

### PR DESCRIPTION
**Pull request by andyli**
This is an attempt of adding Windows support to the existing Haxe community support.
Running individual commands on my Windows VM seems to work correctly.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
This has been deployed to https://staging.travis-ci.com/. I apologize in advance that this may have to be deployed over without notice.

**Comment by andyli** [comment]
I've just added some fixes, would you deploy to staging again?

**Comment by joepvd** [comment]
@andyli your branch has been deployed to https://staging.travis-ci.com.

**Comment by andyli** [comment]
I tweaked the version announcement format a bit. Hopefully it is good this time. Please deploy to staging again.

**Comment by joepvd** [comment]
It is deployed again.

**Comment by andyli** [comment]
Any chance to have it deployed to staging and let me check again?
I believe it is very close to complete (if not already).

**Comment by andyli** [comment]
It has been almost a year since I open this PR. Let's finish this?

**Comment by BanzaiMan** [comment]
@andyli Sorry about the long delay. We can certainly deploy again, though coordination would be easier if you are on our Slack.

**Comment by andyli** [comment]
Cool. Please send a Slack invite to andy@onthewings.net.

**Pull request merged**
