### PR TITLE
Download the proper Dart SDK on Mac OS X

### PR DESCRIPTION
**Pull request by pylaligand**
Fixes https://github.com/travis-ci/travis-ci/issues/5870

### CODE REVIEW

**Comment by pylaligand** [comment]
@a14n @devoncarew @sethladd

Does anyone know how to test this?

**Comment by pylaligand** [comment]
@BanzaiMan

**Comment by a14n** [comment]
lgtm

**Comment by pylaligand** [comment]
Thanks for merging the change. What's the typical delay between a merge and the change being available in prod?

**Comment by BanzaiMan** [comment]
This has been deployed already.

**Pull request merged**
