### PR TITLE
Update NVM to version 0.31.0

### PR DESCRIPTION
**Pull request by BanzaiMan**
Version 0.31.0 adds support for "odd-versioned" stable releases
such as 5.7 and 5.9.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hangs: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/492314
Succeeds: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/492316

**Comment by BanzaiMan** [comment]
We cannot use `travis-build` templating system, since the `nvm.sh` content is too large to be sent to `echo`.

**Comment by BanzaiMan** [comment]
As a side effect, we add Node.js support for OS X.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-ci/issues/2311

**Comment by ljharb** [comment]
LGTM :+1: copying `nvm.sh` is how i update travis-cookbooks anyways

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-ci/issues/5845.

**Pull request merged**
