### PR TITLE
download D prereleases from S3 instead of from FTP

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Turns out we also mirror the prereleases to our S3.

**Comment by MartinNowak** [comment]
Forgot to ping you @BanzaiMan.

**Comment by MartinNowak** [comment]
I added a commit to account for URL quirks in older pre 2.065.0 releases @BanzaiMan.

**Comment by BanzaiMan** [comment]
@MartinNowak Thanks for the ping. We'll deploy this next Monday.

**Comment by MartinNowak** [comment]
Thanks

**Comment by MartinNowak** [comment]
Will this be deployed today @BanzaiMan?

**Comment by BanzaiMan** [comment]
It is now! Thanks for the reminder.

**Pull request merged**
