### PR TITLE
dotnet: Accept 2.1 for SDK version

### PR DESCRIPTION
**Pull request by JustArchi**
cc @joshua-anderson @akoeplinger @nterry

### CODE REVIEW

**Comment by JustArchi** [comment]
ref: https://www.microsoft.com/net/download/linux-package-manager/ubuntu14-04/sdk-2.1.300

**Comment by JustArchi** [comment]
Looks like remaining failures aren't caused by me, thanks for review.

**Comment by akoeplinger** [comment]
Sigh, they keep changing the version number...

@BanzaiMan can you please merge/deploy this?

**Comment by akoeplinger** [comment]
This PR looks a bit more complete, let's go with that: https://github.com/travis-ci/travis-build/pull/1397

Thanks nonetheless @JustArchi !

**Comment by JustArchi** [comment]
Yes, #1397 looks much better regarding this, thanks!

**Pull request closed without merging**
