### PR TITLE
Added beanstalkd

### PR DESCRIPTION
**Pull request by pavanvamsi3**

### CODE REVIEW

**Comment by pavanvamsi3** [comment]
@BanzaiMan : Can you help me with this?

**Comment by BanzaiMan** [comment]
I don't think we install beanstalkd on the images, so this will not work.

**Comment by pavanvamsi3** [comment]
What if my project requires beanstalk in travis? What is the alternative way?

**Comment by BanzaiMan** [comment]
@pavanvamsi3 You can open an issue at https://github.com/travis-ci/travis-ci/issues.

In the mean time, I suggest using `sudo: required` to install and run beanstalkd.

I'm closing this PR now, since it is not effective.

**Comment by pavanvamsi3** [comment]
@BanzaiMan But if I use sudo: required will it be the new container based infra?

**Comment by BanzaiMan** [comment]
`sudo: required` sends builds to GCE.

**Pull request closed without merging**
