### PR TITLE
Dart Support: Use HTTPS Download URLs

### PR DESCRIPTION
**Pull request by kaendfinger**
- Use HTTPS Download URLs

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Paging @a14n @devoncarew and @sethladd

**Comment by BanzaiMan** [comment]
Seems harmless.

**Comment by kaendfinger** [comment]
@BanzaiMan 99.99% sure they will say it's fine :) The Dart Team has been changing download urls on a lot of things to HTTPS, so I figured why not do it here too :)

**Comment by a14n** [comment]
Looks good to me !

**Comment by kaendfinger** [comment]
@BanzaiMan Are you the one who would be merging this?

**Comment by sethladd** [comment]
Definitely want this. Thank you!

**Comment by BanzaiMan** [comment]
Ooops. Sorry. I'll queue this up for Monday (2015-04-20) deployment.

**Pull request merged**
