### PR TITLE
Make PR clones shallow and don't clone the branch first

### PR DESCRIPTION
**Pull request by aidanhs**
Interim fix for travis-ci/travis-ci#7589. Read that issue for background on the approach here. This PR

 - stops travis cloning a branch we don't care about before cloning the actual PR ref
 - makes sure PR cloning obeys the depth configuration
 - fixes an issue that made https://github.com/travis-ci/travis-build/pull/929 not work (I think?) because it specified assert on the command before the conditional

### CODE REVIEW

**Comment by aidanhs** [comment]
Rebased and seems to be failing on

```
rake aborted!
Could not find releases for tools/godep
/home/travis/build/travis-ci/travis-build/Rakefile:71:in `latest_release_for'
/home/travis/build/travis-ci/travis-build/Rakefile:148:in `block in <top (required)>'
Tasks: TOP => default => update_static_files => public/files/godep_darwin_amd64
```

which I don't think is my fault?

**Comment by aidanhs** [comment]
Forced a rebuild, seems fine now. Any chance of this getting a look at some point? We're seeing network failures on initial clone (over at the Rust repo) that would likely be solved (or at least mitigated) by this.

**Comment by meatballhat** [comment]
@aidanhs Hello and sorry about the very long delay :heart: !  Assuming this work is still relevant and desired, are you willing to take a crack at resolving the conflicts?

**Comment by meatballhat** [comment]
I'm closing this out given the conflicts, and I'm not sure it's still applicable work. Please holler if you would like to see this PR reopened 💖 !

**Pull request closed without merging**
