### PR TITLE
C#: add support for Mono alpha and beta channels

### PR DESCRIPTION
**Pull request by akoeplinger**
A user can target them by specifying "mono: alpha" or "mono: beta" in .travis.yml

### CODE REVIEW

**Comment by akoeplinger** [comment]
/cc @Joshua-Anderson @nterry

@BanzaiMan would be cool to get a deployment on staging so I can try this out :)

**Comment by Joshua-Anderson** [comment]
LGTM! Looks awesome.

**Comment by BanzaiMan** [comment]
We would need accompanying documentation change.

**Comment by akoeplinger** [comment]
@BanzaiMan Sure, I'll make a docs PR soon.

**Comment by akoeplinger** [comment]
Docs PR: https://github.com/travis-ci/docs-travis-ci-com/pull/240

**Pull request merged**
