### PR TITLE
Disable Homebrew auto update

### PR DESCRIPTION
**Pull request by BanzaiMan**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Tested: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/586930#L34

**Comment by BanzaiMan** [comment]
On this image, `brew update` takes 210 seconds. https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/586939#L271

**Comment by BanzaiMan** [comment]
This should be documented.

**Comment by BanzaiMan** [comment]
Oh, our current document recommends running `brew update`. :-/

**Comment by peterp** [comment]
Auto update still seems to be run? Do I have to explicitly turn it off?

**Pull request merged**
