### PR TITLE
Perl 5.30 alias

### PR DESCRIPTION
**Pull request by cotsog**
As per https://travisci.zendesk.com/agent/tickets/7831

### CODE REVIEW

**Comment by cotsog** [comment]
I think we'll need to first have the language archive i.e.

`perl: 5.30` on Trusty: https://travis-ci.org/cotsog/travis_ci_prod_regular/jobs/537884400#L396-L401
`perl: 5.30` on Xenial: https://travis-ci.org/cotsog/travis_ci_prod_regular/jobs/537884401#L143-L148

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/travis-nightly-builder/jobs/538205128

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/perl-builder/builds/538205944
https://travis-ci.org/travis-ci/perl-builder/builds/538205980

**Comment by BanzaiMan** [comment]
It could take a little while before the archives are copied to GCS.

**Pull request merged**
