### PR TITLE
[R] Add --no-manual to r_build_args when latex: false

### PR DESCRIPTION
**Pull request by yutannihilation**
`R CMD build` usually doesn't build PDF manuals. But, if the manual contains `\Sexprs{}` macro, it does, and it will end up an error when `latex: false` (e.g. https://github.com/tidyverse/dplyr/pull/4085#issuecomment-451810489).

This PR adds `--no-manual` to `r_build_args` as well to avoid the error. (But, sorry, I don't know how to test this...)

### CODE REVIEW

**Comment by BanzaiMan** [comment]
@jimhester Review, please!

**Comment by jimhester** [comment]
I think it looks ok, but https://github.com/travis-ci/travis-build/pull/1478/files should probably be merged first, and I think this PR should also use `+` rather than `<<` to avoid the repeated `--no-manual` problem.

**Comment by yutannihilation** [comment]
Thanks, I'll fix after it's merged.

**Comment by jimhester** [comment]
LGTM

**Comment by yutannihilation** [comment]
Thanks!

**Pull request merged**
