### PR TITLE
Update Nix to 2.3.1

### PR DESCRIPTION
**Pull request by curiousleo**
Published 2019-10-10, see https://nixos.org/releases/nix/

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Needs a corresponding docs change to https://docs.travis-ci.com/user/languages/nix#default-nix-version

**Comment by curiousleo** [comment]
> Needs a corresponding docs change to https://docs.travis-ci.com/user/languages/nix#default-nix-version

Thanks @BanzaiMan for pointing that out! I've created a docs PR here: https://github.com/travis-ci/docs-travis-ci-com/pull/2578

**Comment by BanzaiMan** [comment]
@domenkozar @garbas @matthewbauer @grahamc 

Feedback, please.

**Comment by BanzaiMan** [comment]
I'll go ahead and merge this.

**Comment by domenkozar** [comment]
This will break macOS.

**Comment by BanzaiMan** [comment]
@domenkozar Oh? How would it? I'll go ahead and revert this, then.

**Comment by curiousleo** [comment]
> This will break macOS.

What? How? I'm sorry! I didn't mean to break macOS. Please revert this PR.

**Comment by domenkozar** [comment]
macOS used to be multi-user by default, so we should probably revert the multi-user changes as we upgrade.

**Pull request merged**
