### PR TITLE
Point PHP 'nightly' to '7.0snapshot'

### PR DESCRIPTION
**Pull request by BanzaiMan**
'master' has moved on to 7.1.0-dev

This resolves https://github.com/travis-ci/travis-ci/issues/4814

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Test build on staging: https://staging.travis-ci.org/BanzaiMan/travis_staging_test

**Comment by GrahamCampbell** [comment]
Why?

**Comment by GrahamCampbell** [comment]
Surely nightly is meant to be 7.1.x now?

**Comment by BanzaiMan** [comment]
Ooops. The title was wrong. It's 7.1.0-dev for nightly.

**Comment by GrahamCampbell** [comment]
Ah right. :+1: then. ;)

**Pull request merged**
