### PR TITLE
Add retry logic to the dart sdk curl request

### PR DESCRIPTION
**Pull request by jakemac53**
For now I set this to 5 retries, with the default exponential backoff (will end up being 1, 2, 4, 8, 16 seconds between failures), and a connection timeout of 15 seconds (connection timeouts are the main failures I have seen).

cc @kevmoo

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @BanzaiMan @a14n – we're getting a LOT of failures downloading our SDK – we're hoping retry helps this...

**Comment by jakemac53** [comment]
@a14n how can we validate this before rolling it out?

**Comment by a14n** [comment]
@jakemac53 sorry I don't know what is the current way to do that. @BanzaiMan ?

**Comment by joepvd** [comment]
@jakemac53 
Just deployed this branch to our staging environment.

To give it a spin, we'd recommend to create a new testing repository, and hook it up with https://staging.travis-ci.org.
Be aware that it is not recommended to have the same repository pointing to both the production and the staging environment.

Please leave a link to a build log in the comments here.

Much appreciated!

**Comment by jakemac53** [comment]
https://staging.travis-ci.org/jakemac53/build/builds/722615

**Comment by jakemac53** [comment]
Looks like the logs aren't actually available and there are some failures though, not sure if you have a way of diagnosing that?

**Pull request merged**
