### PR TITLE
Change default arguments of pip install in python.rb 

### PR DESCRIPTION
**Pull request by 2fasc**
Set default of pip install arguments to '''pip install --progress-bar off -r''' to mitigate issues raised in https://travis-ci.community/t/large-pip-installs-exceed-maximum-log-length/1599/8

### CODE REVIEW

**Comment by 2fasc** [comment]
I dont't understand this Failure. Could somebody help me out here?

Failures:
  1) Travis::Build::Script::Python behaves like a bash script full docker container execution runs and passes
     Failure/Error: expect(log_minus_header).to match(/^Done\. Your build exited with 0\./)
     
     
system_info
       Diff:
       @@ -1,2 +1,456 @@
       -/^Done\. Your build exited with 0\./

**Comment by adamjstewart** [comment]
This issue should have been solved by #1629

**Comment by BanzaiMan** [comment]
The error is coming from `pip`'s failure to execute, e.g., https://travis-ci.org/travis-ci/travis-build/jobs/518833458#L1183, and the consequential failure to look for the matching line to ensure that the script we generate exits properly.

It is not clear to me if #1629 properly fixed the issue with the progress bar; at least, there is an indication that it didn't.

**Comment by 2fasc** [comment]
> It is not clear to me if #1629 properly fixed the issue with the progress bar; at least, there is an indication that it didn't.

At least not for me - I looked at the raw log file and the progress bar is still present and floods the log.

**Comment by joepvd** [comment]
I think the pips bundled with most of the python's on Trusty are too old to listen to the environment variable (and to react to the option on the command line).

I think on the Xenial images, pip should be fresh enough so the environment variable should be adhered to. Could you run a build with `dist: xenial` and see if the progress bars disappear?

**Comment by 2fasc** [comment]
> I think on the Xenial images, pip should be fresh enough so the environment variable should be adhered to. Could you run a build with `dist: xenial` and see if the progress bars disappear?

I tried it and it works! Thank you!

**Comment by adamjstewart** [comment]
Ah, that explains why my PR worked for me.

**Pull request closed without merging**
