### PR TITLE
Install PostgreSQL on demand

### PR DESCRIPTION
**Pull request by BanzaiMan**
See https://github.com/travis-ci/travis-ci/issues/4264.

With 9.3 (already installed, so nothing happens): https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/469792

With 9.5: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/469801#L78

Notice that 9.5 is configured on port 5433, which might be a problem.

Note that we do not install PostGIS.

### CODE REVIEW

**Comment by joshk** [comment]
should we install postgis?
9.5 uses a different port?

**Comment by BanzaiMan** [comment]
When it starts, though, it seems to bind to port 5432. https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/469801#L136

So this is probably fine.

**Comment by BanzaiMan** [comment]
PostGIS is not available from the usual PPA. https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-ci/issues/5445 might also be relevant (re: PostGIS).

**Comment by gildegoma** [comment]
I jump into the discussion to put my "two" cents:

* By default the pgdg apt packages sequentially assign a specific tcp port for each postgresql installations (e.g. 5432 for the first installations, then 5433, etc.)
* As decided with @joshk, the travis `postgresql` chef cookbook has been "designed" to make all preinstalled versions using the default port (5432), and ensure that only one postgresql server can be started at the same time. We also override some postgresql settings for CI context. See https://github.com/travis-ci/travis-cookbooks/pull/221 for (many) more details.
* It is still unsure that PostGIS 2.1 will be officially supported for 9.5. As mentioned in https://github.com/travis-ci/travis-cookbooks/pull/651, upgrading to PostGIS 2.2 might be a good choice when introducing the preinstalled PostgreSQL 9.5

With all the above elements, I am not totally sure whether it is a good idea to "officially" help PostgreSQL installations on demand via `travis-build` as it could lead to new sources of confusion. "Warned" users can run the `apt-get install` commands they want, but then they are aware that the behaviour is a bit "out of travis support control".

**Comment by gildegoma** [comment]
@BanzaiMan I think that your 9.5 instance only listened to 5433. It works because you connect via this port actually: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/469801#L138-L139

**Comment by BanzaiMan** [comment]
Going to close this for now. There are some issues raised by @gildegoma that needs addressed.

**Pull request closed without merging**
