### PR TITLE
actually write cache on PR builds

### PR DESCRIPTION
**Pull request by rkh**

### CODE REVIEW

**Comment by joshk** [comment]
how is the cache url constructed? does it use the branch name or pr number?

**Comment by rkh** [comment]
PR number, see https://github.com/travis-ci/travis-build/pull/305

**Comment by joshk** [comment]
Ahhhh, coolio, thanks.

If we merge this in today are you cool with deploying this to .org and .com?

**Comment by rkh** [comment]
Sure. Just keep in mind that I'll be gone tomorrow.

**Comment by joshk** [comment]
Ok, might be good to pass this to Team Blue then?

**Comment by rkh** [comment]
Maybe. Team Blue is still offline.

**Comment by joshk** [comment]
Well, offline as in ‘asleep’




Dan and Hiro should be back soon, well, online soon :)


—

**Pull request merged**
