### PR TITLE
Ensure $PATH is prepended with a few entries

### PR DESCRIPTION
**Pull request by meatballhat**
to ease development in container-based infrastructure.

### CODE REVIEW

**Comment by sethvargo** [comment]
:+1:

**Comment by BanzaiMan** [comment]
Could you motivate this a little more clearly? What issues were there without this? Do we have related GitHub issues?

**Comment by meatballhat** [comment]
@BanzaiMan we get a decent amount of "support noise" about these two PATH entries, one of which has been partly addressed at the build env image layer [citation needed].  By adding these entries by default, it removes the need for folks in container-based infrastructure in particular from having to add the entries themselves given they aren't able to install into `/usr/bin` or `/usr/local/bin`.

**Comment by BanzaiMan** [comment]
Ah, OK. The citation you seek is https://github.com/travis-ci/travis-cookbooks/blob/master/ci_environment/travis_build_environment/files/default/ci_user/xdg_path.sh.

**Pull request merged**
