### PR TITLE
Echo build and job id as part of system info at beginning of build

### PR DESCRIPTION
**Pull request by igorwwwwwwwwwwwwwwwwwwww**

### CODE REVIEW

**Comment by joshk** [comment]
Hey @igorwwwwwwwwwwwwwwwwwwww, could you give some context on why you think this would be good to add?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Totes. For single job builds it's very hard to find the build id, which is needed to start a debug build via the API. Instead of having to go DOM diving (what support currently suggests) having it in the logs would be quite helpful.

**Comment by joshk** [comment]
Ok, sounds fair.

Just to note, this may be removed in the future once we add a proper `debug job` button, and some tweaks to the UI which may include this information.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@BanzaiMan could you take a look? :)

**Pull request merged**
