### PR TITLE
Add retries for language archive downloads

### PR DESCRIPTION
**Pull request by BanzaiMan**
To reduce the effects of flaky network conditions

### CODE REVIEW

**Comment by BanzaiMan** [comment]
We could also add a config value for the number of retries, instead of hard coding 2.

**Comment by BanzaiMan** [comment]
https://travis-ci.community/t/travis-python-archive-download-is-flaky/2147

**Comment by webknjaz** [comment]
Hi @BanzaiMan, 
In distributed systems it's usually worth having a bit more complicated logic. It's usually a good practice to use exponential backoff for calculating delays.

Here's a pure bash implementation of an exponential backoff, feel free to reuse it:
https://github.com/webknjaz/ansible-gentoo-laptop/blob/master/vault/cat-keybase.sh

**Comment by BanzaiMan** [comment]
@webknjaz My understanding is that `curl`'s `--retry` does exponential backoff by itself.

https://curl.haxx.se/docs/manpage.html#--retry

> When curl is about to retry a transfer, it will first wait one second and then for all forthcoming retries it will double the waiting time until it reaches 10 minutes which then will be the delay between the rest of the retries. By using --retry-delay you disable this exponential backoff algorithm. See also --retry-max-time to limit the total time allowed for retries.

**Comment by BanzaiMan** [comment]
2 is probably insufficient for the issues we're seeing.

**Comment by webknjaz** [comment]
Oh, fair enough! How about 5 retries?

**Pull request closed without merging**
