### PR TITLE
Install Cargo Audit in Rust Environment

### PR DESCRIPTION
**Pull request by naftulikay**
This will install Cargo Audit in the Rust build environment, allowing auditing of Cargo dependencies for security flaws.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Is this a standard tool? I don't know if it is CI's job to do this. If the user wants it, it is easy enough to add.

**Comment by naftulikay** [comment]
So the main issue right now is the installation of `cargo-audit` is an extremely expensive operation (like 10 minute compilation).

@tarcieri and I were discussing this [on Twitter](https://twitter.com/bascule/status/1187818904598372352) and unfortunately right now there are no provided `cargo-audit` binaries available, so installation takes time. There's a way to reduce compilation time by caching it, thankfully.

I'm not sure what the standard practice is with security scanning of dependencies: do environments like NodeJS include the `npm audit` command? If these types of things are those that are always opt-in, then we can probably close this.

**Comment by tarcieri** [comment]
The forthcoming stabilization of the `cargo install-update` command should simplify caching:

https://github.com/RustSec/cargo-audit/issues/143

**Comment by BanzaiMan** [comment]
> unfortunately right now there are no provided cargo-audit binaries available, so installation takes time.

Am I correct to understand that this is going to add "time" to every build? That doesn't seem fair.

Also, the command

    cargo install --force cargo-audit

fails.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/607886989#L206

**Comment by tarcieri** [comment]
@BanzaiMan the minimum supported Rust version for `cargo-audit` is 1.36.0

Regarding adding time to each build, unless the result can be cached, I don't think it makes sense

**Comment by BanzaiMan** [comment]
@tarcieri The command failed on 1.38.0. https://travis-ci.org/BanzaiMan/travis_production_test/builds/607886989#L169

In the end, I tend to think this is not something CI should do. If the user wants it, they can ensure that the version requirement is met, choose to cache binary files if necessary, and so on.

**Comment by naftulikay** [comment]
Yeah I agree and don't see adding a lot of time to the build as being acceptable.

**Comment by tarcieri** [comment]
@BanzaiMan looks like 1.30 to me:

> rustc 1.30.0-nightly (d5a448b3f 2018-08-13)

The error indicates a pre-2018 edition version of Rust. 1.31 was the first version to support the 2018 edition

**Comment by BanzaiMan** [comment]
@tarcieri Hmmm. That's interesting (and strange). I'll look into it.

At any rate… Is there a reason to keep this open?

**Comment by tarcieri** [comment]
If there's no way to cache the install, I'd say close it.

**Comment by naftulikay** [comment]
Yeah, let's close. I was thinking that the Travis environment was similar to Circle CI where images are baked ahead of time but it seems that Travis just runs everything every time.

**Pull request closed without merging**
