### PR TITLE
Add support for mutliple R versions

### PR DESCRIPTION
**Pull request by jimhester**
This PR includes the changes in https://github.com/travis-ci/travis-build/pull/618 however because it is a significant feature I thought it best to open a new PR so it can be tested.

It would be great to deploy this to staging whenever is convenient.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Expanding multiple R versions into a build matrix requires changes in travis-ci/travis-core: see, for example: https://github.com/travis-ci/travis-core/pull/416.

**Comment by jimhester** [comment]
Ah ok good to know. Currently I have the yaml key as `R`, should I change that to `r` to conform to the rest of the languages or is `R` ok, or is it case insensitive?

**Comment by jimhester** [comment]
@BanzaiMan Would it be possible to deploy https://github.com/jimhester/travis-build/commit/f35a7de9f6f5f87382ddd2326189e1d687e9bd23 to staging so I can test things?

**Comment by BanzaiMan** [comment]
@jimhester This has been deployed to staging along with https://github.com/travis-ci/travis-core/pull/517.

**Comment by jimhester** [comment]
Fixed a bug with https://github.com/travis-ci/travis-build/commit/f67c1010c9277a4607f31e514682fb29a82a9a7d, could you deploy that as well!

**Pull request merged**
