### PR TITLE
Switch to rustup.rs

### PR DESCRIPTION
**Pull request by BanzaiMan**
Resolves https://github.com/travis-ci/travis-ci/issues/7276.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Tested here: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/555300

**Comment by QuietMisdreavus** [comment]
Should the initial rustup command be `rustup default [version]`? Just running `rustup install` will download the toolchain but not actually make it the default, so projects that expect nightly-only features will still run on stable. See [this build log someone posted on the Rust IRC](https://travis-ci.org/SethDusek/define-rust/builds/213998300) for an example.

**Comment by BanzaiMan** [comment]
Our apologies.

Is

```
rustup default $TRAVIS_RUST_VERSION
```

sufficient for it?

Could you open a new issue, so that we can track it? Thank you!

**Comment by QuietMisdreavus** [comment]
Yup, that'll work just fine! I'll get that issue opened up.

**Pull request merged**
