### PR TITLE
start mongodb service on xenial

### PR DESCRIPTION
**Pull request by ghatwala**
As seen in the travis build log - https://travis-ci.org/grooverdan/travis-test/jobs/399396033#L366 , mongodb service does not start. as service name is mongodb.service https://packages.ubuntu.com/xenial/ppc64el/mongodb-server/filelist.

### CODE REVIEW

**Comment by ghatwala** [comment]
@meatballhat - please let me know your review comments if any on above PR.

**Comment by joepvd** [comment]
Hi @ghatwala! Thanks!
I hope to merge https://github.com/travis-ci/travis-build/pull/1425 later today, which probably resolves the issues you are addressing as well.

**Comment by ghatwala** [comment]
@joepvd  - that would  be good , will validate it once u merge + deploy.

**Comment by joepvd** [comment]
Appreciated, @ghatwala!

#1425 is live now. Please let us know if you'd run into anything.

**Pull request closed without merging**
