### PR TITLE
Add Haxe support.

### PR DESCRIPTION
**Pull request by andyli**
TravisCI is getting popular in the Haxe community so it would be great if Travis can add community support of the Haxe language :)

I have looked through the PRs of other community supported languages and drafted here a minimal version for haxe.
I manually inspected the shell script produced by `travis compile` and it looks correct to me.

I open this PR to get some feedbacks. If everything is ok I will add docs and other relevant PRs to travis-yaml etc.

Since Haxe compiles to multiple targets, haxe library authors would need to install quite a lot of other things in order to actually run the haxe-compiled output (take a look at [the .travis.yml of buddy](https://github.com/ciscoheat/buddy/blob/master/.travis.yml)). I plan to create a haxe image to preinstall all the common things to ease this, once the basic minimal support is done.

### CODE REVIEW

**Comment by joshk** [comment]
@BanzaiMan @meatballhat @henrikhodne hey hey hey, do we have time this week to review this PR?

**Comment by BanzaiMan** [comment]
I'll take a look soon-ish.

**Comment by BanzaiMan** [comment]
@andyli Hello. I can deploy this to staging tomorrow, April 1, around 13:00 UTC. Go to https://staging.travis-ci.org/ and set up a test repository there to test it, please. If tomorrow does not work, please indicate a time and date that works for you. Thank you!

**Comment by andyli** [comment]
Yes, I'm available at that time. Please let me know when I'm ready to test.
Thanks!

**Comment by BanzaiMan** [comment]
@andyli Thanks. I'm looking into problems with processing jobs on staging. Sorry about the delay.

**Comment by andyli** [comment]
I have tried to create a build at https://staging.travis-ci.org/andyli/HaxeCI/
But seems like there is still problem on starting the build?

**Comment by BanzaiMan** [comment]
The staging environment is working correctly now. I've deployed this PR to staging. You can restart the builds that failed, or push a new commit.

**Comment by andyli** [comment]
I've just fixed a few things (see commit messages) and hopefully it should work now.
One question, do I have to config anything such that a build matrix would be created if multiple values are given to `haxe` in ".travis.yml"?

e.g.
```
language: haxe
haxe:
  - "3.1.3"
  - "development"
```
[My test build](https://staging.travis-ci.org/andyli/HaxeCI/builds/429887) shows 
```
An error occurred while compiling the build script: undefined method `gsub' for ["3.1.3", "development"]:Array
```
The error probably comes from [this line](https://github.com/andyli/travis-build/commit/d94777b8d307d6b0f53a2856d6e38c167cc4f00f#diff-aba99acbee82f10564b08b5136a1470cR104) of the haxe.rb script.

**Comment by BanzaiMan** [comment]
@andyli That is a part that needs to be handled in travis-core. See a similar PR like [this one](https://github.com/travis-ci/travis-core/pull/416).

**Comment by andyli** [comment]
I see. I will make a PR there after this has been merged. Thanks!

**Comment by andyli** [comment]
@BanzaiMan Let me know once you've sync my new commits to staging, please. I will test again and report. Thanks!

**Comment by BanzaiMan** [comment]
Hello, @andyli! I've deployed @137c806 to staging. Please test it.

**Comment by andyli** [comment]
I've pushed some more fixes. Would you sync them to staging please?

**Comment by BanzaiMan** [comment]
@andyli Hi there! @17d2bc1 has been deployed to staging.

**Comment by andyli** [comment]
I confirm that it works nicely now :D

**Comment by andyli** [comment]
BTW, is it possible for me to test multi-os? Or specify it to run on Mac instead of Linux?
Right now I've tested only Linux builds, but Mac builds should work too.

**Pull request merged**
