### PR TITLE
Abort builds if Sauce Connect blocks for > 2 min.

### PR DESCRIPTION
**Pull request by DylanLacey**
Builds opening a Sauce Connect tunnel currently block until Sauce
Connect has produced a readyfile.  In some cases there is no readyfile
producted; This blocks the build until the global no-output timer (10
minutes as of this commit) terminates it.

Readyfiles are produced once a Sauce Connect tunnel is fully up.  This
can fail to happen for a variety of reasons, including the user having
too many tunnels open at once.

This commit introduces a 2 minute wait time (as advised by @ldx, Sauce
Labs employee and total Sauce Connect smart guy) for the readyfile,
after which the entire build is terminated.

The `travis_jigger` function is used to post a notification to the
console and then ultimately kill the process via `travis_terminate 2`
(similarly to `travis_assert`).  An earlier revision used `travis_wait`
but this produced confusing output.

This commit closes https://github.com/travis-ci/travis-ci/issues/3091.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
[This simple test](https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/493922) shows that it works (the timeout of 2 minutes is respected, since the build has incorrect credentials). Ideally, there is a better way to detect that the credentials are invalid and the tunnel is never going to come up.

**Comment by bootstraponline** [comment]
> Ideally, there is a better way to detect that the credentials are invalid

Make [a REST API call](https://wiki.saucelabs.com/display/DOCS/The+Sauce+Labs+REST+API) to Sauce?

**Comment by DanielHeath** [comment]
Almost none of the variable interpolations in this file are quoted, so if there are space characters anywhere you'll be in trouble. 

Compare:
`while [ ! -f ${readyfile} ]; do` 
`while [ ! -f "${readyfile}" ]; do`

If `$readyfile` is set to `missingfile || echo 'hacked you'`, the former will print 'hacked you' to the console while the latter will not.

**Comment by DylanLacey** [comment]
Making a REST API call is a good approach for credentials, but the problem I was trying to solve was the generalised problem of Sauce Connect start up problems.  This can happen for a variety of reasons, some detectable in advance (assuming nothing changes between checks and actual start up, which takes several seconds) and some not.

Currently, an issue starting Sauce Connect will cause a build to hang until Travis's hung build timeout is reached, at which point the entire build is terminated.  This change should account for _most_ problems, known or otherwise, and end builds in 2 minutes, 5 times faster then the default.

@DanielHeath good call; I'll have a whack at correcting that and send an updated PR.

**Comment by DylanLacey** [comment]
Globbing updated;  I left it out for arguments that can't have spaces.

**Comment by BanzaiMan** [comment]
OK. Let's test this again tomorrow (July 15).

**Comment by tristanbes** [comment]
what's the status of this PR please ?

**Comment by meatballhat** [comment]
I'm sorry for the long delay!  This PR is no longer applicable.  Please holler if you feel it should be reopened, assuming the problems haven't been addressed elsewhere.

**Pull request closed without merging**
