### PR TITLE
Remove unneeded user mode in R script

### PR DESCRIPTION
**Pull request by jimhester**
Now that we are installing texlive to the home directory there is no
need to force user mode.

@BanzaiMan Could you deploy this to staging?

### CODE REVIEW

**Comment by jimhester** [comment]
@BanzaiMan could you deploy this to staging, this PR contains a fix for a bug (https://github.com/jimhester/travis-build/commit/9d7599cc125883250fedabf25984192d4bf8cf3b#diff-5b7e1aa01f1c6f058df6e0b9e2486c62R381) that is causing the R builds on staging to fail unconditionally.

**Comment by BanzaiMan** [comment]
@jimhester Sorry about the delay. This has been deployed to staging.

**Comment by jimhester** [comment]
@BanzaiMan No worries, https://github.com/travis-ci/travis-build/commit/27e3017ad1ec9c186ce99ee5574b3bfc74044ac8 puts more of the build output in folds. Could you deploy it to staging when you can, thanks!

**Comment by BanzaiMan** [comment]
@a054622 has been deployed to staging.

**Pull request merged**
