### PR TITLE
Fold Julia installation log

### PR DESCRIPTION
**Pull request by simonbyrne**
This should make it easier to read the logs, especially on OS X where hdiutil spits out a bunch of noise.

### CODE REVIEW

**Comment by simonbyrne** [comment]
cc @tkelman @ninjin @staticfloat

**Comment by tkelman** [comment]
lgtm, didn't see this. weren't we going to have you take over as co maintainer in place of either Pontus or Elliot?

**Comment by simonbyrne** [comment]
I'd be happy to: is there anything I need to do?

**Comment by tkelman** [comment]
Add your name to the announce and docs, I think.

**Pull request merged**
