### PR TITLE
Bump latest R version to 3.6.2

### PR DESCRIPTION
**Pull request by nealrichardson**
R 3.6.2 was released on December 12: https://stat.ethz.ch/pipermail/r-announce/2019/000647.html

cc @jeroen @jimhester

### CODE REVIEW

**Comment by jeroen** [comment]
I think you also need to update some tests, see last bump: https://github.com/travis-ci/travis-build/commit/dd70629817e0cb618b7ace364f7bb096418b1004

**Comment by nealrichardson** [comment]
Tests updated

**Comment by jimhester** [comment]
Thanks, I have now built the binaries for R 3.6.2, so this LGTM.

**Comment by jeroen** [comment]
This is good to go 🚀

**Pull request merged**
