### PR TITLE
Improve SonarQube addon configuration

### PR DESCRIPTION
**Pull request by dbmeneses**
The improvements to the SonarQube addon are described in these 3 tickets:
- https://jira.sonarsource.com/browse/MMF-349
- https://jira.sonarsource.com/browse/MMF-383
- https://jira.sonarsource.com/browse/MMF-384

In addition to the rspec tests, we have integration tests for it that simulate most of the use cases:
https://github.com/SonarSource/travis-build-test

### CODE REVIEW

**Comment by BanzaiMan** [comment]
@dbmeneses This has been deployed to staging.

**Comment by BanzaiMan** [comment]
@dbmeneses Have you had a chance to test this?

**Comment by bellingard** [comment]
@BanzaiMan It's on my side, and I'm just back from holidays. I'll do it next week!

**Comment by BanzaiMan** [comment]
@bellingard OK. I'm off to Japan next week, and I might be slow in responding. It might take a while to coordinate, but we should be able to find some time to test this.

**Comment by BanzaiMan** [comment]
This has been deployed again to .org staging.

**Comment by bellingard** [comment]
Hi @dbmeneses, I've started testing the feature and I've got some issues with key encryption.

Let's take the following repo as an example: https://github.com/FabOrga/multi-language-project. Here's the scenario: 
1. I've encrypted a SonarQube token following https://docs.travis-ci.com/user/encryption-keys/#Usage (I encrypted it in the correct GitHub repository)
2. I've specified the encrypted value in the `.travis.yml` file (see [line #7](https://github.com/FabOrga/multi-language-project/blob/master/.travis.yml#L7)) like this is expected to be supported by the latest developments of the add-on
3. I output the $SONARQUBE_SCANNER_PARAMS environment variable that is supposed to contain the decrypted value of the token (see [line #13](https://github.com/FabOrga/multi-language-project/blob/master/.travis.yml#L13))
4. But when the staging instance executes the job, we can see that the token is not decrypted (see [line #96 in the logs](https://staging.travis-ci.org/FabOrga/multi-language-project#L96))

Any idea why this does not work?

**Comment by dbmeneses** [comment]
@BanzaiMan do secure variables get replaced by the decrypted values in the parsed YAML when using the staging? 
As @bellingard reported, it doesn't seem to be the case. I also get the raw encrypted values during the build.

**Comment by BanzaiMan** [comment]
Sorry for the delay. I've been traveling the last couple of weeks. I'll take a look at this PR next week!

**Comment by BanzaiMan** [comment]
@dbmeneses Encrypting for staging requires a different API endpoint from the one used for production. Using a wrong API endpoint renders the encrypted value invalid and the build won't see the decrypted value.

To encrypt, try:

    travis encrypt -e https://api-staging.travis-ci.org -r FabOrga/multi-language-project

**Comment by dbmeneses** [comment]
@BanzaiMan It appears that this p/r is not included in the staging anymore. 
I've rebased this p/r on master and changed the sonarqube scanner cli version, which fixes a problem found during testing with the staged addon (https://jira.sonarsource.com/browse/TRAVIS-4). Could you please deploy it again in staging so that we can do the final testing?

**Comment by BanzaiMan** [comment]
@dbmeneses Sorry about that. I've deployed it again. Thanks.

**Comment by dbmeneses** [comment]
@BanzaiMan @bellingard I've rebased on master again and fixed the spec tests. I've tried secure variables, they are working: https://staging.travis-ci.org/dbmeneses/sonarqube-addon-test

**Comment by bellingard** [comment]
@BanzaiMan Looks like you've not deployed the latest version that includes modifications of this PR. The following line in the logs shows that the currently deployed version is the same as the production one: https://staging.travis-ci.org/FabTemp/multi-language-project/builds/513386#L150

**Comment by BanzaiMan** [comment]
Sorry about that. Staging can be in an unpredictable state. I'm waiting to deploy it now, pending Heroku's issue (https://twitter.com/herokustatus/status/779302180020822016).

**Comment by BanzaiMan** [comment]
OK. It's been deployed again.

**Comment by bellingard** [comment]
@BanzaiMan Looks like the new deployment did not work correctly. The version of the SonarQube Scanner that is downloaded is "2.7-build314" (see https://staging.travis-ci.org/FabTemp/multi-language-multi-module-project/builds/513499#L149) whereas version "2.8" is specified in @dbmeneses 's latest commits (see https://github.com/travis-ci/travis-build/pull/831/files#diff-1ef94773b86865fbc2213f4860ea73f0R10). 
So looks like the Staging is still in an unpredictable state. :-/

**Comment by BanzaiMan** [comment]
Sorry about the delay. Could you test this again? Thanks.

**Comment by dbmeneses** [comment]
@BanzaiMan , the addon deployed in staging has some problems that we don't understand.
It seems that it's not succeeding downloading the scanner-cli 2.8. This could be explained if the deployed addon didn't have the latest fix before 95913a8, which fixed the usage of the maven central repository.

Could you please confirm that the addon deployed in staging is the commit 95913a8, and re-deploy if necessay? 
Also, are there any restrictions to download external files in staging?

The P/R has currently changes to init.rb that should be dropped (committed by mistake), but I won't do changes until we figure out why testing is failing.

Thanks!

**Comment by BanzaiMan** [comment]
@dbmeneses There must have been some merge conflict I did not resolve correctly. I re-merged the test branch and deployed it. Could you try again?

Thank you.

**Comment by bellingard** [comment]
@BanzaiMan Looks like the Add-on is now working as expected, I'll be able to keep on doing my validation tomorrow. Thanks!

**Comment by BanzaiMan** [comment]
Is this ready?

**Comment by dbmeneses** [comment]
No, I will do a last fix today. I will let you know when it's ready.

**Comment by bellingard** [comment]
@BanzaiMan Staging is again back to a non up-to-date state regarding this PR. :-/ For instance, I relaunched a job that used to work 2 days ago and now I can see that the Add-on is back to the "prod" version (see https://staging.travis-ci.org/FabTemp/multi-language-project/builds/513548#L150). 

I'm almost done with the validation - so hopefully we can get the PR on the staging back so that I can finish and the PR can finally be merged!

**Comment by BanzaiMan** [comment]
Hello. Sorry for the delay. I've deployed this to staging again.

**Comment by dbmeneses** [comment]
@BanzaiMan The addon is not running on external pull requests. Reading https://github.com/travis-ci/travis-ci/issues/2135, it seems that the sonarqube addon needs to be on a whitelist so that it runs on external p/r. Is that correct?

**Comment by bellingard** [comment]
FYI @BanzaiMan, when the SonarQube addon is in the whitelist, then I will have to only do a latest test and we will be done!

**Comment by BanzaiMan** [comment]
Since SonarQube (generally) needs secrets to function, I do not think it is a good idea to allow it in PR builds from forks. See https://github.com/travis-ci/travis-ci/issues/1946, as well as https://docs.travis-ci.com/user/jwt and https://github.com/travis-ci/travis-ci/issues/6569.

**Comment by BanzaiMan** [comment]
Is further testing required?

**Comment by bellingard** [comment]
@BanzaiMan Not executing the add-on in PR builds from forks changes a couple of things, so if you don't allow this, we'll have to make some new changes unfortunately. :-/

Still, before we try to change something, I'd just like to clarify what the add-on is supposed to do on external PR: it won't pass any secret at all but only 1 parameter (i.e. no sensitive information) that disables the SonarQube analysis to not break the builds of external PR. You can check that in the code of the add-on (I think this is pretty straightforward for you to validate this). Why we're doing this? Just to keep the YML file as simple and not require end-user to check wether or not they should execute the SonarQube analysis. 

With this clarification on how the add-on is working, can you reconsider @dbmeneses's request to activate it on external PR?
If it's still not clear, we can plan a Skype if you want to discuss this further. We are extremely cautious about security concerns (we operate our own cloud service too!) so I'm pretty sure we can show you that the add-on is safe.

**Comment by BanzaiMan** [comment]
Sorry for the delay. The code to remove that one Maven build phase looks good. I have deployed this to https://staging.travis-ci.org/.

**Comment by bellingard** [comment]
@BanzaiMan The add-on is indeed deployed on https://staging.travis-ci.org, but still not activated on external pull requests.

You can see it here: https://staging.travis-ci.org/FabTemp/multi-language-project/builds/513650
- There's nothing in the log that shows the activation of the Add-on
- The Maven "sonar:sonar" build phase breaks the analysis whereas we would expect to just be silently skipped

**Comment by BanzaiMan** [comment]
@bellingard Please try again.

**Comment by dbmeneses** [comment]
@BanzaiMan I've changed the P/R to fix a problem we found with unsecured pull requests. Could you please deploy it once again in staging so that we can do the final validation?

**Comment by BanzaiMan** [comment]
Sorry for the delay. We will get to this in an hour or so.

**Comment by BanzaiMan** [comment]
Deployed to staging.

**Comment by dbmeneses** [comment]
Thanks @BanzaiMan. The addon is not doing what it should on unsecured pull requests and we don't know why. 
Could you please check if the addon is still in the whitelist and that the latest commit (46eeab3) is deployed?

**Comment by BanzaiMan** [comment]
I think the staging scheduler may not include what production does (with respect to PRs from forks). Is there anything else to address?

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-scheduler/pull/51 has been deployed to .org staging. Sonarqube addon should now work on external PRs. (Only to be skipped by the addon itself.)

**Comment by bellingard** [comment]
@BanzaiMan I confirm that it's working! 👍  So my validation is done on this PR. :-D

I will now work on the update of the documentation so that we can go to production ASAP.

**Comment by BanzaiMan** [comment]
We are going to deploy this on Monday.

**Comment by BanzaiMan** [comment]
This has been deployed to production.

**Comment by bellingard** [comment]
Thanks @BanzaiMan :-), I can now use it live!

**Comment by bbockelm** [comment]
Hey - it seems that the code has been deployed but the Travis-CI documentation hasn't been updated to match.  Took some wild guessing to figure out what was going wrong when I tried to follow the docs.

**Comment by bellingard** [comment]
@bbockelm I'm currently working on the documentation. New version is supposed to be backward compatible with previous one, so not sure that the issue you faced is due to documentation.

**Comment by bbockelm** [comment]
Hit two issues(-ish):
1.  Was trying to add this to an existing project as a PR from an external repo.  Dunno if it worked in the old version, but it definitely isn't allowed in the new one (probably a tripwire that deserves a mention in the docs).
2.  I figured (1) out from reading the code and then put the branch in the primary repo, then hit the fact that, even though I had `sonar.branch` set right in `sonar-project.properties`, I didn't have it set in the `.travis.yml`.

I now got SonarQube's scanner working, but am currently trying to figure out a permission-denied issue when it is uploading results (https://travis-ci.org/singularityware/singularity/builds/178443079#L1846).  I'm guessing something is wrong with my token, but it's not entirely clear.  So close!

**Comment by bbockelm** [comment]
Ah - and if you start with a fresh project `foo:bar` and analyze a branch named `baz`, then you get the permission denied:

https://travis-ci.org/singularityware/singularity/builds/178447624#L2260

(but in SonarQube it auto-creates a project named `foo:bar:baz`.

However, if you manually set the project key to `foo:bar:baz` in the sonar properties file, it will upload to the correct project name and succeed:

https://travis-ci.org/singularityware/singularity/builds/178447831#L2323

So, I'm not entirely sure the branches feature is working correctly: I have to change `sonar-project.properties` for each active branch by hand (either that or it's just an issue for fresh projects?).

**Comment by bellingard** [comment]
@bbockelm Please come on the SonarQube Google group to talk about this - I will answer there. This PR is not the place for that kind of discussion.

**Pull request merged**
