### PR TITLE
nix: retry installation due to travis-ci/travis-ci#7636

### PR DESCRIPTION
**Pull request by domenkozar**
Until travis-ci figures out the root cause for SSL errors, let's just retry.

cc @garbas and @matthewbauer

### CODE REVIEW

**Comment by domenkozar** [comment]
@BanzaiMan

**Comment by domenkozar** [comment]
@BanzaiMan doesn't it retry the whole line? Is there a way to make it retries the whole line, including the pipe?

**Comment by domenkozar** [comment]
@BanzaiMan I've changed logic to use wget. How can I test this one? /cc @matthewbauer

**Comment by BanzaiMan** [comment]
@domenkozar If you have a repository set up on https://staging.travis-ci.org, we can set up a time to test it there. Would that work for you?

**Comment by domenkozar** [comment]
That works. Anytime in CET timezone is fine

**Comment by BanzaiMan** [comment]
Great. This has been deployed there now.

**Comment by BanzaiMan** [comment]
I need to use staging here and there. If you don't see your code in effect, that's the reason.

**Comment by domenkozar** [comment]
It doesn't seem to be deployed now: https://staging.travis-ci.org/hercules-ci/hercules#L163

**Comment by domenkozar** [comment]
@BanzaiMan ping me once it's back up (I'll be around for next 4h).

**Comment by domenkozar** [comment]
@BanzaiMan correction, I have only 1h left today.

**Comment by BanzaiMan** [comment]
@domenkozar Sorry about the delay. It is there now.

**Comment by domenkozar** [comment]
@BanzaiMan I missed a bug, can you redeploy?

**Comment by BanzaiMan** [comment]
@domenkozar Done. Could you send your email to support@travis-ci.com, so that we can invite you to our Slack? It'll make our real-time communication easier.

**Comment by domenkozar** [comment]
Done. It works: https://staging.travis-ci.org/hercules-ci/hercules/builds/579398

**Pull request merged**
