### PR TITLE
Bump Go and gimme versions

### PR DESCRIPTION
**Pull request by AlekSi**
Poke @BanzaiMan.

Resolves https://github.com/travis-ci/travis-ci/issues/7857.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Please update the specs, too.

**Comment by msoap** [comment]
@AlekSi please update https://github.com/travis-ci/travis-build/blob/master/spec/build/script/go_spec.rb

**Comment by AlekSi** [comment]
@BanzaiMan @msoap Done.

**Comment by AlekSi** [comment]
See #1148.

**Pull request closed without merging**
