### PR TITLE
Backport 832 for 2.0: Introduce TRAVIS_BUILD_APT_WHITELIST_SKIP env var

### PR DESCRIPTION
**Pull request by bnferguson**
This backports #832.

Conflicting files:
- lib/travis/build/addons/apt.rb
- spec/build/addons/apt_spec.rb

cc @BanzaiMan

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hmmm. Those are some unhappy conflicts. I'll take a look.

**Comment by bnferguson** [comment]
@BanzaiMan - I reworked the PR (but not the specs yet) to try to capture the intent of the original. Thoughts?

**Comment by bnferguson** [comment]
@BanzaiMan - OK, I think this is ready for review now. I took a different approach. Bit by bit I realized I was rewriting more and more of what was already in master and this addon is pretty nicely isolated. So pulled in the master changes in this file and the spec and things seem to be checking out. What ends up coming in with it is the `paranoid` bits, which I'm not familiar with, otherwise it seems to be only the things we need. 

Mind taking another pass at it review wise? The big thing that I'm wondering now is will I need to pass in anything besides the `TRAVIS_BUILD_APT_WHITELIST_SKIP` env var in the Enterprise config. 

And will there be any issue with the lack of paranoid or `disable_sudo?` coming in on the data payload? (they should both default to nil either way right?)

**Comment by bnferguson** [comment]
@BanzaiMan - I've tested this and it seems to work, if you have a moment today, do you mind giving it a quick once over review wise since the change is much larger now? I've confirmed how it behaves for my first concern up there, but still curious about: 

> And will there be any issue with the lack of paranoid or `disable_sudo?` coming in on the data payload? (they should both default to nil either way right?)

Thank youuuuuu! ⚡

**Pull request merged**
