### PR TITLE
postgresql install from repo - any version

### PR DESCRIPTION
**Pull request by grooverdan**
closes travis-ci/travis-ci/issues/4264

### CODE REVIEW

**Comment by joshk** [comment]
We already have 9.1, 9.2 and 9.3 preinstalled. Before merging this we need to look into how this would affect these preinstalled versions, and if we should maybe remove some of them.

**Comment by meatballhat** [comment]
I need to get it documented, but a PR merged yesterday makes 9.5 installation work on container based with existing addons, fwiw.

**Comment by joshk** [comment]
Hmmmm, ok, we can talk about this on Monday then.

**Comment by meatballhat** [comment]
working build: https://staging.travis-ci.org/meatballhat/yolo-octo-adventure/builds/433553
corresponding config: https://github.com/meatballhat/yolo-octo-adventure/blob/5b2db2f53e2a8dbd599f067b8dc85addaa26aae0/.travis.yml

having to set PGPORT=5433 is arguably a wart :smiley_cat:

**Comment by BanzaiMan** [comment]
@joshk @meatballhat We need to look into https://github.com/travis-ci/travis-ci/issues/4570.

**Comment by meatballhat** [comment]
@BanzaiMan true, but that's unrelated to this PR :smiley_cat:

**Comment by BanzaiMan** [comment]
@meatballhat Ha, 'tis true. Commented on the appropriate one. Sorry for the noise.

**Comment by grooverdan** [comment]
> Hmmmm, ok, we can talk about this on Monday then.

FYI its Monday

**Comment by freesteph** [comment]
any update on this? can't get PG 9.5 to work on my instance, it seems like it resets the auth method to `peer` instead of `trust` which makes `before_script` database setup impossible.

**Comment by grooverdan** [comment]
seems 9.6 is there now http://apt.postgresql.org/pub/repos/apt/pool/9.6/p/postgresql-9.6/ . Don't know why 9.5 isn't there now.

**Comment by BanzaiMan** [comment]
@grooverdan Thanks for the reminder. I've opened #587 to supersede this.

**Comment by grooverdan** [comment]
all superceeded

**Pull request closed without merging**
