### PR TITLE
[dart] handle tests written with the new test package

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by kevmoo** [comment]
Awesome! LGTM!

**Comment by kevmoo** [comment]
@BanzaiMan can you look at this?

**Comment by BanzaiMan** [comment]
Sorry for the delay. I was on vacation.

**Comment by a14n** [comment]
No problem. Thanks!

**Comment by a14n** [comment]
@BanzaiMan there seems to be an issue with `sh.elif` and `raw:true`.

The following code

```
sh.elif '[[ -d packages/unittest ]] || ( [[ -f .packages ]] && grep -q "^unittest:" .packages )', raw: true do
```

leads to error : 

```
/home/travis/build.sh: line 301: `elif [[ [[ -d packages/unittest ]] || ( [[ -f .packages ]] && grep -q "^unittest:" .packages ) ]]; then'
```

It should have been `elif [[ -d packages/unittest ]] || ( [[ -f .packages ]] && grep -q "^unittest:" .packages ); then`

see https://travis-ci.org/a14n/zengen/jobs/86390640

**Comment by BanzaiMan** [comment]
There seems to be a bug in handling `elif`. I'll take a look.

**Comment by BanzaiMan** [comment]
@a14n I've deployed @svenfuchs's PR that fixes this issue to staging. Could you test it? Thanks.

**Comment by a14n** [comment]
Works fine on staging : https://staging.travis-ci.org/a14n/zengen/jobs/445856
Thanks

**Comment by kevmoo** [comment]
Thanks so much, @a14n !

**Pull request merged**
