### PR TITLE
Add TRAVIS_COMMIT_MESSAGE

### PR DESCRIPTION
**Pull request by BanzaiMan**
which will be defined at runtime

Resolves https://github.com/travis-ci/travis-ci/issues/965.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Some environment variables are best defined at runtime, because it could contain non-ASCII characters and cause problems. Here, we set `$TRAVIS_COMMIT_MESSAGE` by asking `git` at runtime, rather than depending on GitHub's payload.

`$TRAVIS_BRANCH` *may* also benefit (see https://github.com/travis-ci/travis-ci/issues/1376) from this approach, but I am a little hesitant to do that just yet.

**Comment by BanzaiMan** [comment]
Tested https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/534179.

**Comment by cvrebert** [comment]
You probably don't want the --no-merges part in the general case.

**Comment by BanzaiMan** [comment]
@cvrebert Thanks.

**Comment by joshk** [comment]
Great work Hiro. It feels like a bit of a pity that we need to defer to git for this info, but if it works it works.

**Pull request merged**
