### PR TITLE
Fix GemStone-related problems [Smalltalk]

### PR DESCRIPTION
**Pull request by fniephaus**
Unfortunately, we still haven't been able to run GemStone tests successfully on a container due to a couple of problems.
Since Docker doesn't support `hostname` changes within the container, we now just add the `hostname` to `/etc/hosts` which should work just fine as well.
This PR also fixes some bugs that keep the script from installing GemStone dependencies and it removes some redundant folds.

/cc @dalehenrich

### CODE REVIEW

**Comment by BanzaiMan** [comment]
@fniephaus Is this ready for merge?

**Comment by fniephaus** [comment]
Yes, I think so. Unfortunately, there is no way to test/debug this, but I hope GemStone builds will finally work after this.
Thanks!

**Comment by BanzaiMan** [comment]
@fniephaus Let's test this next week.

**Comment by fniephaus** [comment]
No worries, I don't have any time to play around with it this week anyway.

**Comment by fniephaus** [comment]
Can we get this in before the weekend? That'd be awesome!

**Comment by BanzaiMan** [comment]
Sorry for the delay. This has been deployed to production.

**Pull request merged**
