### PR TITLE
make latex optional

### PR DESCRIPTION
**Pull request by jeroenooms**

### CODE REVIEW

**Comment by jimhester** [comment]
LGTM

**Comment by BanzaiMan** [comment]
Needs a corresponding docs PR.

**Comment by jimhester** [comment]
@jeroenooms The relevant doc is https://github.com/travis-ci/docs-travis-ci-com/edit/gh-pages/user/languages/r.md

**Comment by jeroenooms** [comment]
@BanzaiMan here you go: https://github.com/travis-ci/docs-travis-ci-com/pull/645

**Comment by BanzaiMan** [comment]
Will be deployed tomorrow.

**Comment by BanzaiMan** [comment]
Actually, it's done now.

**Pull request merged**
