### PR TITLE
Allow to specify caching timeout

### PR DESCRIPTION
**Pull request by drogus**
This allows to set timeout for cacher with:

```
cache:
  timeout: 1000
```

### CODE REVIEW

**Comment by svenfuchs** [comment]
:+1: 

Saw this on support before, so I'm all for merging this, and adding it to the docs.

**Comment by lukeyeager** [comment]
Is that in minutes?

**Comment by BanzaiMan** [comment]
@lukeyeager Seconds.

**Comment by lukeyeager** [comment]
That's what I thought. Can you explain why I have caches that are months old even though I set the timeout to be 1 week?

https://github.com/NVIDIA/DIGITS/blob/v4.0.0-rc.3/.travis.yml#L18

**Pull request merged**
