### PR TITLE
Ensure github.com SSH host key exists in ~/.ssh/known_hosts

### PR DESCRIPTION
**Pull request by BanzaiMan**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Tests:

On OS X: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/468888
On Linux: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/468897

Neither hangs, though the attempt to clone over SSH fails similarly.

**Comment by joshk** [comment]
Hmmmmmmm :/

**Comment by BanzaiMan** [comment]
@joshk Could you explain your "hmmm"?

**Comment by BanzaiMan** [comment]
I don't think this is an issue at the moment.

**Pull request closed without merging**
