### PR TITLE
Assert `apt-get install` commands

### PR DESCRIPTION
**Pull request by BanzaiMan**
APT packages are most likely critical to the build's success,
and so if the installation fails, notify the user

Upon install failure, we show `apt-get update` output

### CODE REVIEW

**Comment by BanzaiMan** [comment]
This would inform users of potential issues with `apt-get update` (which I believe was a cause of https://github.com/travis-ci/travis-ci/issues/5617).

**Comment by BanzaiMan** [comment]
Test: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/491727

**Comment by BanzaiMan** [comment]
Also see #605.

**Comment by joshk** [comment]
Looks good to me

**Pull request merged**
