### PR TITLE
Fix .NET Core support on macOS.

### PR DESCRIPTION
**Pull request by aidmsu**
Now if you try to build .NET Core app on macOS you'll get an exception:
```
System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
It relates to known [issue](https://github.com/dotnet/corefx/issues/9171).

To solve this problem it's necessary to do the following:
```Fish shell
~$ mkdir -p /usr/local/lib
~$ ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
~$ ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```
Moreover, official [.NET Core installation guide](https://www.microsoft.com/net/core#macos) tells that you should run commands desribed above before using .NET Core on macOS.

So, this PR adds this commands which will be perform on macOS before installing .NET Core.

### CODE REVIEW

**Comment by aidmsu** [comment]
I found out that an instruction `brew link --force openssl` is depricated and  instructions
```Fish shell
~$ mkdir -p /usr/local/lib
~$ ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
~$ ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```
are just instead of `brew link --force openssl`.

This problem is discussed in this PR: [Homebrew/brew#597](https://github.com/Homebrew/brew/pull/597).

So I added one more commit to remove this instruction.

**Comment by BanzaiMan** [comment]
Please set up a repo on https://staging.travis-ci.org so that we can coordinate testing this PR.

**Comment by aidmsu** [comment]
@BanzaiMan I set up [aidmsu/Hangfire](https://github.com/aidmsu/Hangfire) repo. It has two PR: [PR#2](https://github.com/aidmsu/Hangfire/pull/3) and [PR#3](https://github.com/aidmsu/Hangfire/pull/3). [PR#3](https://github.com/aidmsu/Hangfire/pull/3) contains commands to link to openssl libs and [build](https://staging.travis-ci.org/aidmsu/Hangfire/jobs/532597) is successful on macOS . [PR#2](https://github.com/aidmsu/Hangfire/pull/3)  doesn't contain the commands and [build](https://staging.travis-ci.org/aidmsu/Hangfire/jobs/532592) failed on macOS.

**Comment by BanzaiMan** [comment]
Because it is not deployed. I'll let you know when.

**Comment by BanzaiMan** [comment]
I plan to deploy this to staging around 15:00 UTC tomorrow.

**Comment by aidmsu** [comment]
@BanzaiMan Thanks! I'm looking forward to it.

**Comment by BanzaiMan** [comment]
@aidmsu This has been deployed to staging.

**Comment by aidmsu** [comment]
@BanzaiMan I restarted [build](https://staging.travis-ci.org/aidmsu/Hangfire/jobs/532592) of [PR#2](https://github.com/aidmsu/Hangfire/pull/2) and [it](https://staging.travis-ci.org/aidmsu/Hangfire/jobs/532592) passed on macOS now!

**Pull request merged**
