### PR TITLE
a few improvements for the D build script

### PR DESCRIPTION
**Pull request by MartinNowak**
- avoid rate limit on github's api
- announce dub version
- use date-independent URLs to download dmd
- support dmd prerelease versions

### CODE REVIEW

**Comment by BanzaiMan** [comment]
@MartinNowak Could you look at the spec failures? Thanks.

**Comment by MartinNowak** [comment]
Fixed, swapped `tail` and `head` in the spec.

**Comment by MartinNowak** [comment]
Thanks to the new `compile` command I was able to test the scripts upfront this time ;).

**Comment by MartinNowak** [comment]
@BanzaiMan

**Comment by MartinNowak** [comment]
thx

**Pull request merged**
